
export interface Blueprint {
  id: string;
  name: string;
  image: string | null; // null = no image, show placeholder asterisk
}

export const BLUEPRINTS_DATA: Blueprint[] = [
  { id: 'extended-shotgun-mag-iii', name: 'Extended Shotgun Mag III', image: '/images/items/Extended_Shotgun_Mag_III.png' },
  { id: 'angled-grip-iii', name: 'Angled Grip III', image: '/images/items/Angled_Grip_III.png' },
  { id: 'pulse-mine', name: 'Pulse Mine', image: '/images/items/Pulse_Mine.webp' },
  { id: 'silencer-ii', name: 'Silencer II', image: '/images/items/Silencer_II.png' },
  { id: 'red-light-stick', name: 'Red Light Stick', image: 'https://arcraiders.wiki/w/images/9/93/Red_Light_Stick.png' },
  { id: 'tactical-mk3-revival', name: 'Tactical Mk. 3 (Revival)', image: '/images/items/Tactical_Mk._3_Revival.png' },
  { id: 'compensator-ii', name: 'Compensator II', image: '/images/items/Compensator_II.png' },
  { id: 'muzzle-brake-iii', name: 'Muzzle Brake III', image: '/images/items/Muzzle_Brake_III.png' },
  { id: 'tactical-mk3-defensive', name: 'Tactical MK.3 (Defensive)', image: '/images/items/Tactical_Mk._3_(Defensive).png' },
  { id: 'vita-spray', name: 'Vita Spray', image: '/images/items/Vita_Spray.png' },
  { id: 'medium-gun-parts', name: 'Medium Gun Parts', image: '/images/items/Medium_Gun_Parts.png' },
  { id: 'tagging-grenade', name: 'Tagging Grenade', image: '/images/items/Tagging_Grenade.png' },
  { id: 'crash-mat', name: 'Crash Mat', image: 'https://arcraiders.wiki/w/images/7/75/Crash_Mat.png' },
  { id: 'bobcat', name: 'Bobcat', image: '/images/items/Bobcat.png' },
  { id: 'defibrillator', name: 'Defibrillator', image: '/images/items/Defibrillator.png' },
  { id: 'jupiter', name: 'Jupiter', image: '/images/items/Jupiter.png' },
  { id: 'extended-medium-mag-ii', name: 'Extended Medium Mag II', image: '/images/items/Extended_Medium_Mag_II.png' },
  { id: 'tactical-mk3-smoke', name: 'Tactical MK.3 (Smoke)', image: 'https://arcraiders.wiki/w/images/d/d6/Tactical_Mk._3_%28Smoke%29.png' },
  { id: 'smoke-grenade', name: 'Smoke Grenade', image: '/images/items/Smoke_Grenade.png' },
  { id: 'dolabra', name: 'Dolabra', image: '/images/items/Dolabra.png' },
  { id: 'shotgun-silencer', name: 'Shotgun Silencer', image: '/images/items/Shotgun_Silencer.png' },
  { id: 'white-flag', name: 'White Flag', image: 'https://arcraiders.wiki/w/images/4/43/White_Flag.png' },
  { id: 'extended-light-mag-ii', name: 'Extended Light Mag II', image: '/images/items/Extended_Light_Mag_II.png' },
  { id: 'showstopper', name: 'Showstopper', image: '/images/items/Showstopper.png' },
  { id: 'remote-raider-flare', name: 'Remote Raider Flare', image: 'https://arcraiders.wiki/w/images/f/ff/Remote_Raider_Flare.png' },
  { id: 'angled-grip-ii', name: 'Angled Grip II', image: '/images/items/Angled_Grip_II.png' },
  { id: 'stable-stock-iii', name: 'Stable Stock III', image: '/images/items/Stable_Stock_III.png' },
  { id: 'aphelion-rifle', name: 'Aphelion Rifle', image: '/images/items/Aphelion.png' },
  { id: 'tempest', name: 'Tempest', image: '/images/items/Tempest.png' },
  { id: 'tactical-mk3-healing', name: 'Tactical MK.3 (Healing)', image: '/images/items/Tactical_Mk._3_Healing.png' },
  { id: 'vertical-grip-iii', name: 'Vertical Grip III', image: '/images/items/Vertical_Grip_III.png' },
  { id: 'wolfpack', name: 'Wolfpack', image: '/images/items/Wolfpack.png' },
  { id: 'combat-mk3-flanking', name: 'Combat Mk. 3 (Flanking)', image: '/images/items/Combat_Mk._3_(Flanking).png' },
  { id: 'torrente', name: 'Torrente', image: '/images/items/Torrente.png' },
  { id: 'jolt-mine', name: 'Jolt Mine', image: '/images/items/Jolt_Mine.png' },
  { id: 'hullcracker', name: 'Hullcracker', image: '/images/items/Hullcracker.png' },
  { id: 'vita-shot', name: 'Vita Shot', image: '/images/items/Vita_Shot.png' },
  { id: 'deadline', name: 'Deadline', image: '/images/items/Deadline.png' },
  { id: 'shotgun-choke-ii', name: 'Shotgun Choke II', image: '/images/items/Shotgun_Choke_II.png' },
  { id: 'anvil', name: 'Anvil', image: '/images/items/Anvil.png' },
  { id: 'osprey', name: 'Osprey', image: '/images/items/Osprey.png' },
  { id: 'looting-mk3-survivor', name: 'Looting MK. 3 (Survivor)', image: '/images/items/Looting_Mk._3_(Survivor).png' },
  { id: 'extended-shotgun-mag-ii', name: 'Extended Shotgun Mag II', image: '/images/items/Extended_Shotgun_Mag_II.png' },
  { id: 'powered-descender', name: 'Powered Descender', image: 'https://arcraiders.wiki/w/images/2/21/Powered_Descender.png' },
  { id: 'compensator-iii', name: 'Compensator III', image: '/images/items/Compensator_III.png' },
  { id: 'vulcano', name: 'Vulcano', image: '/images/items/Vulcano.png' },
  { id: 'lightweight-stock', name: 'Lightweight Stock', image: '/images/items/Lightweight_Stock.png' },
  { id: 'trailblazer-grenade', name: 'Trailblazer Grenade', image: '/images/items/Trailblazer.png' },
  { id: 'barricade-kit', name: 'Barricade Kit', image: '/images/items/Barricade_Kit.png' },
  { id: 'green-light-stick', name: 'Green Light Stick', image: 'https://arcraiders.wiki/w/images/2/27/Green_Light_Stick.png' },
  { id: 'extended-medium-mag-iii', name: 'Extended Medium Mag III', image: '/images/items/Extended_Medium_Mag_III.png' },
  { id: 'lure-grenade', name: 'Lure Grenade', image: '/images/items/Lure_Grenade.webp' },
  { id: 'combat-mk3-aggressive', name: 'Combat Mk.3 (Aggressive)', image: '/images/items/Combat_Mk._3_(Aggressive).png' },
  { id: 'light-gun-parts', name: 'Light Gun Parts', image: '/images/items/Light_Gun_Parts.png' },
  { id: 'extended-light-mag-iii', name: 'Extended Light Mag III', image: '/images/items/Extended_Light_Mag_III.png' },
  { id: 'il-toro', name: 'Il Toro', image: '/images/items/Il_Toro.png' },
  { id: 'padded-stock', name: 'Padded Stock', image: '/images/items/Padded_Stock.png' },
  { id: 'heavy-gun-parts', name: 'Heavy Gun Parts', image: '/images/items/Heavy_Gun_Parts.png' },
  { id: 'canto', name: 'Canto', image: '/images/items/Canto.png' },
  { id: 'bettina', name: 'Bettina', image: '/images/items/Bettina.png' },
  { id: 'fireworks-box', name: 'Fireworks Box', image: 'https://arcraiders.wiki/w/images/0/0f/Fireworks_Box.png' },
  { id: 'gas-mine', name: 'Gas Mine', image: '/images/items/Gas_Mine.png' },
  { id: 'yellow-light-stick', name: 'Yellow Light Stick', image: 'https://arcraiders.wiki/w/images/1/1f/Yellow_Light_Stick.png' },
  { id: 'looting-mk3-safekeeper', name: 'Looting MK. 3 (Safekeeper)', image: '/images/items/Looting_Mk._3_(Safekeeper).png' },
  { id: 'surge-coil', name: 'Surge Coil', image: '/images/items/Surge_Coil.png' },
  { id: 'complex-gun-parts', name: 'Complex Gun Parts', image: '/images/items/Complex_Gun_Parts.png' },
  { id: 'explosive-mine', name: 'Explosive Mine', image: '/images/items/Explosive_Mine.png' },
  { id: 'venator', name: 'Venator', image: '/images/items/Venator.png' },
  { id: 'stable-stock-ii', name: 'Stable Stock II', image: '/images/items/Stable_Stock_II.png' },
  { id: 'blaze-grenade', name: 'Blaze Grenade', image: '/images/items/Blaze_Grenade.png' },
  { id: 'trigger-nade', name: 'Trigger Nade', image: "/images/items/Trigger_'Nade.png" },
  { id: 'seeker-grenade', name: 'Seeker Grenade', image: '/images/items/Seeker_Grenade.png' },
  { id: 'silencer-i', name: 'Silencer I', image: '/images/items/Silencer_I.png' },
  { id: 'shotgun-choke-iii', name: 'Shotgun Choke III', image: '/images/items/Shotgun_Choke_III.png' },
  { id: 'blue-light-stick', name: 'Blue Light Stick', image: 'https://arcraiders.wiki/w/images/c/cc/Blue_Light_Stick.png' },
  { id: 'vertical-grip-ii', name: 'Vertical Grip II', image: '/images/items/Vertical_Grip_II.png' },
  { id: 'muzzle-brake-ii', name: 'Muzzle Brake II', image: '/images/items/Muzzle_Brake_II.png' },
  { id: 'extended-barrel', name: 'Extended Barrel', image: '/images/items/Extended_Barrel.png' },
  { id: 'burletta', name: 'Burletta', image: '/images/items/Burletta.png' },
  { id: 'equalizer', name: 'Equalizer', image: '/images/items/Equalizer.png' },
  { id: 'snap-hook', name: 'Snap Hook', image: '/images/items/Snap_Hook.png' },
];
