
export interface Blueprint {
  id: string;
  name: string;
  image: string | null; // null = no image, show placeholder asterisk
}

export const BLUEPRINTS_DATA: Blueprint[] = [
  { id: 'extended-shotgun-mag-iii', name: 'Extended Shotgun Mag III', image: '/images/items/Extended_Shotgun_Mag_III.webp' },
  { id: 'angled-grip-iii', name: 'Angled Grip III', image: '/images/items/Angled_Grip_III.webp' },
  { id: 'pulse-mine', name: 'Pulse Mine', image: '/images/items/Pulse_Mine.webp' },
  { id: 'silencer-ii', name: 'Silencer II', image: '/images/items/Silencer_II.webp' },
  { id: 'red-light-stick', name: 'Red Light Stick', image: '/images/items/Red_Light_Stick.webp' },
  { id: 'tactical-mk3-revival', name: 'Tactical Mk. 3 (Revival)', image: '/images/items/Tactical_Mk._3_Revival.webp' },
  { id: 'compensator-ii', name: 'Compensator II', image: '/images/items/Compensator_II.webp' },
  { id: 'muzzle-brake-iii', name: 'Muzzle Brake III', image: '/images/items/Muzzle_Brake_III.webp' },
  { id: 'tactical-mk3-defensive', name: 'Tactical MK.3 (Defensive)', image: '/images/items/Tactical_Mk._3_(Defensive).webp' },
  { id: 'vita-spray', name: 'Vita Spray', image: '/images/items/Vita_Spray.webp' },
  { id: 'medium-gun-parts', name: 'Medium Gun Parts', image: '/images/items/Medium_Gun_Parts.webp' },
  { id: 'tagging-grenade', name: 'Tagging Grenade', image: '/images/items/Tagging_Grenade.webp' },
  { id: 'crash-mat', name: 'Crash Mat', image: '/images/items/Crash_Mat.webp' },
  { id: 'bobcat', name: 'Bobcat', image: '/images/items/Bobcat.webp' },
  { id: 'defibrillator', name: 'Defibrillator', image: '/images/items/Defibrillator.webp' },
  { id: 'jupiter', name: 'Jupiter', image: '/images/items/Jupiter.webp' },
  { id: 'extended-medium-mag-ii', name: 'Extended Medium Mag II', image: '/images/items/Extended_Medium_Mag_II.webp' },
  { id: 'tactical-mk3-smoke', name: 'Tactical MK.3 (Smoke)', image: '/images/items/Tactical_Mk._3_(Smoke).webp' },
  { id: 'smoke-grenade', name: 'Smoke Grenade', image: '/images/items/Smoke_Grenade.webp' },
  { id: 'dolabra', name: 'Dolabra', image: '/images/items/Dolabra.webp' },
  { id: 'shotgun-silencer', name: 'Shotgun Silencer', image: '/images/items/Shotgun_Silencer.webp' },
  { id: 'white-flag', name: 'White Flag', image: '/images/items/White_Flag.webp' },
  { id: 'extended-light-mag-ii', name: 'Extended Light Mag II', image: '/images/items/Extended_Light_Mag_II.webp' },
  { id: 'showstopper', name: 'Showstopper', image: '/images/items/Showstopper.webp' },
  { id: 'remote-raider-flare', name: 'Remote Raider Flare', image: '/images/items/Remote_Raider_Flare.webp' },
  { id: 'angled-grip-ii', name: 'Angled Grip II', image: '/images/items/Angled_Grip_II.webp' },
  { id: 'stable-stock-iii', name: 'Stable Stock III', image: '/images/items/Stable_Stock_III.webp' },
  { id: 'aphelion-rifle', name: 'Aphelion', image: '/images/items/Aphelion.webp' },
  { id: 'tempest', name: 'Tempest', image: '/images/items/Tempest.webp' },
  { id: 'tactical-mk3-healing', name: 'Tactical MK.3 (Healing)', image: '/images/items/Tactical_Mk._3_Healing.webp' },
  { id: 'vertical-grip-iii', name: 'Vertical Grip III', image: '/images/items/Vertical_Grip_III.webp' },
  { id: 'wolfpack', name: 'Wolfpack', image: '/images/items/Wolfpack.webp' },
  { id: 'combat-mk3-flanking', name: 'Combat Mk. 3 (Flanking)', image: '/images/items/Combat_Mk._3_(Flanking).webp' },
  { id: 'torrente', name: 'Torrente', image: '/images/items/Torrente.webp' },
  { id: 'jolt-mine', name: 'Jolt Mine', image: '/images/items/Jolt_Mine.webp' },
  { id: 'hullcracker', name: 'Hullcracker', image: '/images/items/Hullcracker.webp' },
  { id: 'vita-shot', name: 'Vita Shot', image: '/images/items/Vita_Shot.webp' },
  { id: 'deadline', name: 'Deadline', image: '/images/items/Deadline.webp' },
  { id: 'shotgun-choke-ii', name: 'Shotgun Choke II', image: '/images/items/Shotgun_Choke_II.webp' },
  { id: 'anvil', name: 'Anvil', image: '/images/items/Anvil.webp' },
  { id: 'osprey', name: 'Osprey', image: '/images/items/Osprey.webp' },
  { id: 'looting-mk3-survivor', name: 'Looting MK. 3 (Survivor)', image: '/images/items/Looting_Mk._3_(Survivor).webp' },
  { id: 'extended-shotgun-mag-ii', name: 'Extended Shotgun Mag II', image: '/images/items/Extended_Shotgun_Mag_II.webp' },
  { id: 'powered-descender', name: 'Powered Descender', image: '/images/items/Powered_Descender.webp' },
  { id: 'compensator-iii', name: 'Compensator III', image: '/images/items/Compensator_III.webp' },
  { id: 'vulcano', name: 'Vulcano', image: '/images/items/Vulcano.webp' },
  { id: 'lightweight-stock', name: 'Lightweight Stock', image: '/images/items/Lightweight_Stock.webp' },
  { id: 'trailblazer-grenade', name: 'Trailblazer', image: '/images/items/Trailblazer.webp' },
  { id: 'barricade-kit', name: 'Barricade Kit', image: '/images/items/Barricade_Kit.webp' },
  { id: 'green-light-stick', name: 'Green Light Stick', image: '/images/items/Green_Light_Stick.webp' },
  { id: 'extended-medium-mag-iii', name: 'Extended Medium Mag III', image: '/images/items/Extended_Medium_Mag_III.webp' },
  { id: 'lure-grenade', name: 'Lure Grenade', image: '/images/items/Lure_Grenade.webp' },
  { id: 'combat-mk3-aggressive', name: 'Combat Mk.3 (Aggressive)', image: '/images/items/Combat_Mk._3_(Aggressive).webp' },
  { id: 'light-gun-parts', name: 'Light Gun Parts', image: '/images/items/Light_Gun_Parts.webp' },
  { id: 'extended-light-mag-iii', name: 'Extended Light Mag III', image: '/images/items/Extended_Light_Mag_III.webp' },
  { id: 'il-toro', name: 'Il Toro', image: '/images/items/Il_Toro.webp' },
  { id: 'padded-stock', name: 'Padded Stock', image: '/images/items/Padded_Stock.webp' },
  { id: 'heavy-gun-parts', name: 'Heavy Gun Parts', image: '/images/items/Heavy_Gun_Parts.webp' },
  { id: 'canto', name: 'Canto', image: '/images/items/Canto.webp' },
  { id: 'bettina', name: 'Bettina', image: '/images/items/Bettina.webp' },
  { id: 'fireworks-box', name: 'Fireworks Box', image: '/images/items/Fireworks_Box.webp' },
  { id: 'gas-mine', name: 'Gas Mine', image: '/images/items/Gas_Mine.webp' },
  { id: 'yellow-light-stick', name: 'Yellow Light Stick', image: '/images/items/Yellow_Light_Stick.webp' },
  { id: 'looting-mk3-safekeeper', name: 'Looting MK. 3 (Safekeeper)', image: '/images/items/Looting_Mk._3_(Safekeeper).webp' },
  { id: 'surge-coil', name: 'Surge Coil', image: '/images/items/Surge_Coil.webp' },
  { id: 'complex-gun-parts', name: 'Complex Gun Parts', image: '/images/items/Complex_Gun_Parts.webp' },
  { id: 'explosive-mine', name: 'Explosive Mine', image: '/images/items/Explosive_Mine.webp' },
  { id: 'venator', name: 'Venator', image: '/images/items/Venator.webp' },
  { id: 'stable-stock-ii', name: 'Stable Stock II', image: '/images/items/Stable_Stock_II.webp' },
  { id: 'blaze-grenade', name: 'Blaze Grenade', image: '/images/items/Blaze_Grenade.webp' },
  { id: 'trigger-nade', name: 'Trigger Nade', image: "/images/items/Trigger_'Nade.webp" },
  { id: 'seeker-grenade', name: 'Seeker Grenade', image: '/images/items/Seeker_Grenade.webp' },
  { id: 'silencer-i', name: 'Silencer I', image: '/images/items/Silencer_I.webp' },
  { id: 'shotgun-choke-iii', name: 'Shotgun Choke III', image: '/images/items/Shotgun_Choke_III.webp' },
  { id: 'blue-light-stick', name: 'Blue Light Stick', image: '/images/items/Blue_Light_Stick.webp' },
  { id: 'vertical-grip-ii', name: 'Vertical Grip II', image: '/images/items/Vertical_Grip_II.webp' },
  { id: 'muzzle-brake-ii', name: 'Muzzle Brake II', image: '/images/items/Muzzle_Brake_II.webp' },
  { id: 'extended-barrel', name: 'Extended Barrel', image: '/images/items/Extended_Barrel.webp' },
  { id: 'extended-barrel-ii', name: 'Extended Barrel II', image: '/images/items/Extended_Barrel_II.webp' },
  { id: 'burletta', name: 'Burletta', image: '/images/items/Burletta.webp' },
  { id: 'equalizer', name: 'Equalizer', image: '/images/items/Equalizer.webp' },
  { id: 'snap-hook', name: 'Snap Hook', image: '/images/items/Snap_Hook.webp' },
];
