import React, { useState, useEffect, useRef, useCallback, useMemo } from 'react';
import html2canvas from 'html2canvas';
import { TradeItem, getAllGameItems, loadAllGameItems, getTradeItemImage, getRarityBorderColor, getRarityHex, getRarityHoverStyles, getRarityGlowStyles, getSourceImageUrls } from '../utils';
import SmartItemIcon from './SmartItemIcon';

interface TradeScreenProps {
  onBack: () => void;
}

interface TradeEntry {
  item: TradeItem;
  quantity: number;
}

const TRADE_COLOR = '#8b5cf6'; // Roxo/Violeta para Trade
const BG_PATH = '/images/background-home.webp';

const TradeExportCard: React.FC<{
  giveList: TradeEntry[];
  receiveList: TradeEntry[];
  exportRef: React.RefObject<HTMLDivElement>;
  imageCache: Record<string, string>;
  intent: 'WTB' | 'WTS';
}> = ({ giveList, receiveList, exportRef, imageCache, intent }) => {
  const lookForBlock = (
    <div style={{ flex: 1, backgroundColor: '#0f172a', padding: '24px', borderRadius: '24px', border: '2px solid #f59e0b44' }}>
      <div style={{ fontSize: '24px', color: '#f59e0b', fontWeight: 900, marginBottom: '20px', textAlign: 'center', letterSpacing: '2px' }}>
        I'M LOOKING FOR
      </div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', justifyContent: 'center' }}>
        {receiveList.map((entry) => (
          <ExportItemCard key={entry.item.id} entry={entry} imageCache={imageCache} />
        ))}
        {receiveList.length === 0 && <div style={{ color: '#64748b', fontSize: '18px' }}>Nothing listed...</div>}
      </div>
    </div>
  );

  const offeringBlock = (
    <div style={{ flex: 1, backgroundColor: '#0f172a', padding: '24px', borderRadius: '24px', border: '2px solid #10b98144' }}>
      <div style={{ fontSize: '24px', color: '#10b981', fontWeight: 900, marginBottom: '20px', textAlign: 'center', letterSpacing: '2px' }}>
        I'M OFFERING
      </div>
      <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', justifyContent: 'center' }}>
        {giveList.map((entry) => (
          <ExportItemCard key={entry.item.id} entry={entry} imageCache={imageCache} />
        ))}
        {giveList.length === 0 && <div style={{ color: '#64748b', fontSize: '18px' }}>Nothing listed...</div>}
      </div>
    </div>
  );

  return (
    <div
      ref={exportRef}
      style={{
        position: 'fixed', left: '-9999px', top: 0,
        width: '1080px', backgroundColor: '#050914',
        padding: '40px', fontFamily: 'sans-serif', boxSizing: 'border-box',
      }}
    >
      <div style={{ textAlign: 'center', marginBottom: '30px' }}>
        <div style={{ fontSize: '16px', color: TRADE_COLOR, letterSpacing: '6px', fontWeight: 900, textTransform: 'uppercase' }}>
          STASH PLANNER
        </div>
        <div style={{ fontSize: '48px', color: '#ffffff', fontWeight: 900, letterSpacing: '2px', fontStyle: 'italic' }}>
          {intent === 'WTB' ? 'WANT TO BUY (WTB)' : 'WANT TO SELL (WTS)'}
        </div>
      </div>

      <div style={{ display: 'flex', gap: '40px' }}>
        {intent === 'WTB' ? (
          <>
            {lookForBlock}
            {offeringBlock}
          </>
        ) : (
          <>
            {offeringBlock}
            {lookForBlock}
          </>
        )}
      </div>

      <div style={{ marginTop: '30px', textAlign: 'center', color: '#475569', fontSize: '12px', letterSpacing: '2px' }}>
        GENERATED BY STASH PLANNER • ARC RAIDERS
      </div>
    </div>
  );
};

const ExportItemCard: React.FC<{ entry: TradeEntry, imageCache: Record<string, string> }> = ({ entry, imageCache }) => {
  const finalSrc = imageCache[entry.item.id] || null;
  const rarityHex = getRarityHex(entry.item.rarity);
  
  return (
    <div style={{
      width: '120px', height: '160px', backgroundColor: '#1e293b', borderRadius: '12px',
      border: `2px solid ${rarityHex}66`, display: 'flex', flexDirection: 'column', overflow: 'hidden'
    }}>
      <div style={{ height: '100px', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '8px' }}>
        {finalSrc ? (
          <img src={finalSrc} style={{ maxWidth: '100%', maxHeight: '100%', objectFit: 'contain' }} alt={entry.item.name} />
        ) : <span style={{ fontSize: '32px', color: '#64748b' }}>?</span>}
      </div>
      <div style={{ flex: 1, backgroundColor: '#00000088', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', padding: '4px' }}>
        <div style={{ fontSize: '10px', color: '#f8fafc', fontWeight: 700, textAlign: 'center', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis', width: '100%' }}>
          {entry.item.name}
        </div>
        <div style={{ fontSize: '14px', color: '#cbd5e1', fontWeight: 900, marginTop: '2px' }}>
          x{entry.quantity}
        </div>
      </div>
    </div>
  );
};

async function preloadImagesForTrade(items: TradeItem[]): Promise<Record<string, string>> {
  const cache: Record<string, string> = {};
  await Promise.all(items.map(async (item) => {
    // Prioritize local images first to avoid CORS issues!
    const urls = [...getSourceImageUrls(item.name)];
    if (item.image && !urls.includes(item.image)) {
      urls.push(item.image);
    }
    if (urls.length === 0) return;
    
    for (const src of urls) {
      try {
        await new Promise<void>((resolve, reject) => {
          const img = new Image();
          // Only use crossOrigin if it's an external URL to prevent local taint issues
          if (src.startsWith('http')) {
            img.crossOrigin = 'anonymous';
          }
          img.onload = () => {
            try {
              const canvas = document.createElement('canvas');
              canvas.width = img.naturalWidth;
              canvas.height = img.naturalHeight;
              const ctx = canvas.getContext('2d')!;
              ctx.drawImage(img, 0, 0);
              cache[item.id] = canvas.toDataURL('image/png');
            } catch { }
            resolve();
          };
          img.onerror = () => reject();
          img.src = src;
        });
        if (cache[item.id]) break; // Successfully loaded and cached!
      } catch {
        // Try next URL
      }
    }
  }));
  return cache;
}

const TradeScreen: React.FC<TradeScreenProps> = ({ onBack }) => {
  const [giveItems, setGiveItems] = useState<TradeEntry[]>([]);
  const [receiveItems, setReceiveItems] = useState<TradeEntry[]>([]);
  const [tradeIntent, setTradeIntent] = useState<'WTB' | 'WTS'>('WTB');
  
  const [isExporting, setIsExporting] = useState(false);
  const [toastMsg, setToastMsg] = useState('');
  const [showExportMenu, setShowExportMenu] = useState(false);
  const [imageCache, setImageCache] = useState<Record<string, string>>({});
  
  const [pickerOpen, setPickerOpen] = useState(false);
  const [pickerTarget, setPickerTarget] = useState<'give' | 'receive' | null>(null);
  const [searchQuery, setSearchQuery] = useState('');
  const [activeCategory, setActiveCategory] = useState<string>('All');
  const [isLoadingItems, setIsLoadingItems] = useState(true);
  const [allItemsList, setAllItemsList] = useState<TradeItem[]>([]);
  const [tempSelection, setTempSelection] = useState<TradeItem[]>([]);

  const CATEGORIES = useMemo(() => [
    { id: 'All', icon: 'apps', label: 'All' },
    { id: 'Weapon', icon: 'swords', label: 'Weapons' },
    { id: 'Material', icon: 'deployed_code', label: 'Materials' },
    { id: 'Blueprint', icon: 'architecture', label: 'Blueprints' },
    { id: 'Mod', icon: 'settings_input_component', label: 'Mods' },
    { id: 'Throwable', icon: 'bomb', label: 'Consumable' },
    { id: 'Augment', icon: 'bolt', label: 'Augments' },
  ], []);

  const exportRef = useRef<HTMLDivElement>(null);
  const exportMenuRef = useRef<HTMLDivElement>(null);

  // Load all 560 items from the ARCTracker database
  useEffect(() => {
    loadAllGameItems().then(items => {
      setAllItemsList(items);
      setIsLoadingItems(false);
    });
  }, []);

  // Close export menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (e: MouseEvent) => {
      if (exportMenuRef.current && !exportMenuRef.current.contains(e.target as Node)) {
        setShowExportMenu(false);
      }
    };
    document.addEventListener('mousedown', handleClickOutside);
    return () => document.removeEventListener('mousedown', handleClickOutside);
  }, []);

  const openPicker = (target: 'give' | 'receive') => {
    setPickerTarget(target);
    setPickerOpen(true);
    setSearchQuery('');
    setTempSelection([]);
  };

  const handleSelectItem = (item: TradeItem) => {
    setTempSelection(prev => {
      if (prev.find(i => i.id === item.id)) {
        return prev.filter(i => i.id !== item.id);
      }
      return [...prev, item];
    });
  };

  const handleConfirmSelection = () => {
    if (!pickerTarget) {
      setPickerOpen(false);
      return;
    }
    const targetSet = pickerTarget === 'give' ? setGiveItems : setReceiveItems;
    targetSet(prev => {
      const newItems = [...prev];
      for (const item of tempSelection) {
        if (!newItems.find(e => e.item.id === item.id)) {
          newItems.push({ item, quantity: 1 });
        }
      }
      return newItems;
    });
    setPickerOpen(false);
  };

  const updateQuantity = (list: 'give' | 'receive', id: string, delta: number) => {
    const targetSet = list === 'give' ? setGiveItems : setReceiveItems;
    targetSet(prev => {
      return prev.map(e => {
        if (e.item.id === id) {
          const newQ = Math.max(0, e.quantity + delta);
          return { ...e, quantity: newQ };
        }
        return e;
      }).filter(e => e.quantity > 0);
    });
  };

  const filteredItems = useMemo(() => {
    let result = allItemsList;
    if (activeCategory !== 'All') {
      result = result.filter(i => i.category === activeCategory);
    }
    if (searchQuery) {
      result = result.filter(i => i.name.toLowerCase().includes(searchQuery.toLowerCase()));
    }
    return result;
  }, [allItemsList, searchQuery, activeCategory]);

  const generateCanvas = useCallback(async () => {
    if (!exportRef.current) return null;
    const allTradeItems = [...giveItems.map(e => e.item), ...receiveItems.map(e => e.item)];
    const cache = await preloadImagesForTrade(allTradeItems);
    setImageCache(cache);
    await new Promise(res => setTimeout(res, 300));
    return html2canvas(exportRef.current, { backgroundColor: '#050914', scale: 2, logging: false });
  }, [giveItems, receiveItems]);

  const showToast = (msg: string) => {
    setToastMsg(msg);
    setTimeout(() => setToastMsg(''), 4000);
  };

  const handleDownload = async () => {
    setIsExporting(true); setShowExportMenu(false);
    try {
      const canvas = await generateCanvas();
      if (!canvas) return;
      const link = document.createElement('a');
      link.download = `StashPlanner-TradeOffer.jpg`;
      link.href = canvas.toDataURL('image/jpeg', 0.92);
      link.click();
    } catch (e) { console.error(e); } finally { setIsExporting(false); }
  };

  const handleShare = async () => {
    setIsExporting(true); setShowExportMenu(false);
    try {
      const canvas = await generateCanvas();
      if (!canvas) return;
      const pngBlob = await new Promise<Blob | null>(res => canvas.toBlob(res, 'image/png'));
      if (navigator.clipboard && (navigator.clipboard as any).write && pngBlob) {
        await (navigator.clipboard as any).write([new ClipboardItem({ 'image/png': pngBlob })]);
        showToast('Image copied! Paste anywhere.');
      } else {
        handleDownload(); // fallback
      }
    } catch (e) { console.error(e); } finally { setIsExporting(false); }
  };

  const renderTradeList = (list: TradeEntry[], type: 'give' | 'receive') => (
    <div className={`flex-1 rounded-3xl p-6 relative overflow-hidden backdrop-blur-sm border-2 ${type === 'give' ? 'border-emerald-500/20 bg-emerald-950/20' : 'border-amber-500/20 bg-amber-950/20'}`}>
      <div className={`absolute top-0 left-0 w-full h-1 bg-gradient-to-r ${type === 'give' ? 'from-emerald-500 to-transparent' : 'from-amber-500 to-transparent'}`} />
      
      <div className="flex justify-between items-center mb-6">
        <div>
          <h3 className={`text-2xl font-black tracking-widest uppercase ${type === 'give' ? 'text-emerald-400' : 'text-amber-400'}`}>
            {type === 'give' ? "I'M OFFERING" : "I'M LOOKING FOR"}
          </h3>
          <p className="text-xs text-slate-400 font-bold uppercase tracking-wider">
            {list.length} Items Listed
          </p>
        </div>
        <button
          onClick={() => openPicker(type)}
          className={`flex items-center gap-2 px-4 py-2 rounded-xl border transition-all ${type === 'give' ? 'bg-emerald-500/10 border-emerald-500/30 hover:bg-emerald-500/20 hover:border-emerald-400 text-emerald-400' : 'bg-amber-500/10 border-amber-500/30 hover:bg-amber-500/20 hover:border-amber-400 text-amber-400'}`}
        >
          <span className="material-symbols-outlined text-sm">add</span>
          <span className="text-xs font-black tracking-widest">ADD</span>
        </button>
      </div>

      <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {list.map((entry) => {
          return (
            <div key={entry.item.id} className={`group relative bg-slate-900/80 rounded-2xl p-3 flex flex-col items-center border border-white/5 hover:border-white/20 transition-all ${getRarityHoverStyles(entry.item.rarity)}`}>
              <div className="w-16 h-16 mb-2 relative">
                {entry.item.image ? (
                  <img src={entry.item.image} alt={entry.item.name} className="w-full h-full object-contain" />
                ) : (
                  <SmartItemIcon itemName={entry.item.name} rarity={entry.item.rarity} imageClassName="w-full h-full object-contain" iconClassName="text-3xl text-slate-600" />
                )}
              </div>
              <div className="text-[10px] font-black text-center text-slate-200 uppercase line-clamp-1 break-words w-full px-1">
                {entry.item.name}
              </div>
              <div className={`mt-3 flex items-center justify-between w-full bg-black/40 rounded-lg p-1 border ${type === 'give' ? 'border-emerald-500/20' : 'border-amber-500/20'}`}>
                <button onClick={() => updateQuantity(type, entry.item.id, -1)} className="w-6 h-6 flex items-center justify-center bg-white/5 hover:bg-white/20 rounded text-slate-300">-</button>
                <span className="text-sm font-black text-white w-8 text-center">{entry.quantity}</span>
                <button onClick={() => updateQuantity(type, entry.item.id, 1)} className="w-6 h-6 flex items-center justify-center bg-white/5 hover:bg-white/20 rounded text-slate-300">+</button>
              </div>
              <button onClick={() => updateQuantity(type, entry.item.id, -999)} className="absolute -top-2 -right-2 w-6 h-6 bg-red-500/90 text-white rounded-full flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity shadow-lg scale-75 hover:scale-100">
                <span className="material-symbols-outlined text-sm">close</span>
              </button>
            </div>
          );
        })}
      </div>
      {list.length === 0 && (
        <div className="flex flex-col items-center justify-center py-16 opacity-30">
          <span className="material-symbols-outlined text-5xl mb-2">inventory_2</span>
          <span className="text-sm font-bold tracking-widest uppercase">List is empty</span>
        </div>
      )}
    </div>
  );

  return (
    <div className="flex-1 flex flex-col relative min-h-screen">
      <TradeExportCard giveList={giveItems} receiveList={receiveItems} exportRef={exportRef} imageCache={imageCache} intent={tradeIntent} />
      
      {toastMsg && (
        <div className="fixed bottom-24 left-1/2 -translate-x-1/2 z-[999] bg-[#0d1b2e] border border-blue-500/40 text-white text-sm font-bold px-6 py-3 rounded-2xl shadow-2xl flex items-center gap-3">
          <span className="material-symbols-outlined text-blue-400">check_circle</span>{toastMsg}
        </div>
      )}

      <main className="flex-1 flex flex-col p-4 md:p-6 pb-32 relative z-10 animate-fade-in w-full mx-auto" style={{ maxWidth: '1400px' }}>
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-8">
          <div className="flex items-center gap-6">
            <button onClick={onBack} className="w-14 h-14 flex items-center justify-center bg-white/5 hover:bg-purple-500/20 rounded-2xl text-slate-400 hover:text-purple-400 transition-all border border-white/10 shadow-2xl">
              <span className="material-symbols-outlined text-3xl">arrow_back</span>
            </button>
            <div>
              <div className="flex bg-white/5 rounded-xl p-1 mb-2 w-fit border border-white/10 shadow-inner">
                <button onClick={() => setTradeIntent('WTB')} className={`px-4 py-1.5 rounded-lg font-black tracking-widest text-xs transition-all ${tradeIntent === 'WTB' ? 'bg-amber-500 text-white shadow-[0_0_15px_rgba(245,158,11,0.4)]' : 'text-slate-400 hover:text-white'}`}>WANT TO BUY</button>
                <button onClick={() => setTradeIntent('WTS')} className={`px-4 py-1.5 rounded-lg font-black tracking-widest text-xs transition-all ${tradeIntent === 'WTS' ? 'bg-emerald-500 text-white shadow-[0_0_15px_rgba(16,185,129,0.4)]' : 'text-slate-400 hover:text-white'}`}>WANT TO SELL</button>
              </div>
              <h2 className="text-4xl md:text-6xl font-black tracking-[0.2em] text-white drop-shadow-glow uppercase italic" style={{ textShadow: '0 0 20px rgba(139, 92, 246, 0.5)' }}>
                TRADE HUB
              </h2>
              <div className="text-xs font-black text-purple-400 tracking-widest mt-1">BUILD YOUR OFFER</div>
            </div>
          </div>
          
          <div className="relative" ref={exportMenuRef}>
            <button
              onClick={() => setShowExportMenu(!showExportMenu)}
              disabled={isExporting || (giveItems.length === 0 && receiveItems.length === 0)}
              className="bg-purple-600 hover:bg-purple-500 border border-purple-400 px-6 py-3 rounded-xl flex items-center gap-2 transition-all disabled:opacity-50 disabled:cursor-not-allowed shadow-[0_0_20px_rgba(139,92,246,0.3)]"
            >
              <span className="material-symbols-outlined">{isExporting ? 'hourglass_empty' : 'ios_share'}</span>
              <span className="text-sm font-black tracking-[0.15em] text-white">{isExporting ? 'GENERATING...' : 'GENERATE OFFER'}</span>
            </button>
            {showExportMenu && (
              <div className="absolute right-0 top-full mt-2 w-56 bg-[#0d1b2e] border border-white/15 rounded-2xl overflow-hidden shadow-2xl z-50">
                <div className="p-1.5 flex flex-col gap-1">
                  <button onClick={handleShare} className="flex items-center gap-3 px-4 py-3 rounded-xl hover:bg-purple-500/20 text-left">
                    <span className="material-symbols-outlined text-purple-400">content_copy</span>
                    <div><div className="text-xs font-black text-white">COPY IMAGE</div><div className="text-[10px] text-slate-500">Paste in Discord</div></div>
                  </button>
                  <button onClick={handleDownload} className="flex items-center gap-3 px-4 py-3 rounded-xl hover:bg-emerald-500/20 text-left">
                    <span className="material-symbols-outlined text-emerald-400">download</span>
                    <div><div className="text-xs font-black text-white">SAVE IMAGE</div><div className="text-[10px] text-slate-500">Download .jpg</div></div>
                  </button>
                </div>
              </div>
            )}
          </div>
        </div>

        <div className="flex flex-col lg:flex-row gap-6 w-full">
          {tradeIntent === 'WTB' ? (
            <>
              {renderTradeList(receiveItems, 'receive')}
              <div className="hidden lg:flex items-center justify-center opacity-30"><span className="material-symbols-outlined text-6xl">sync_alt</span></div>
              {renderTradeList(giveItems, 'give')}
            </>
          ) : (
            <>
              {renderTradeList(giveItems, 'give')}
              <div className="hidden lg:flex items-center justify-center opacity-30"><span className="material-symbols-outlined text-6xl">sync_alt</span></div>
              {renderTradeList(receiveItems, 'receive')}
            </>
          )}
        </div>
      </main>

      {pickerOpen && (
        <div className="fixed inset-0 z-[1000] bg-black/80 backdrop-blur-md flex items-center justify-center p-4">
          <div className="bg-[#0b1325] border border-white/10 rounded-3xl w-full max-w-4xl max-h-[85vh] flex flex-col shadow-2xl overflow-hidden animate-fade-in-up">
            <div className={`p-6 border-b ${pickerTarget === 'give' ? 'border-emerald-500/30 bg-emerald-900/10' : 'border-amber-500/30 bg-amber-900/10'} flex items-center justify-between`}>
              <h3 className={`text-2xl font-black tracking-widest uppercase ${pickerTarget === 'give' ? 'text-emerald-400' : 'text-amber-400'}`}>
                {pickerTarget === 'give' ? "SELECT ITEM TO OFFER" : "SELECT ITEM TO RECEIVE"}
              </h3>
              <div className="flex gap-3">
                {tempSelection.length > 0 && (
                  <button onClick={handleConfirmSelection} className="px-6 py-2 bg-purple-600 hover:bg-purple-500 text-white font-black tracking-widest rounded-xl flex items-center gap-2 transition-all shadow-[0_0_15px_rgba(168,85,247,0.4)]">
                    <span className="material-symbols-outlined">check_circle</span>
                    <span>CONFIRM ({tempSelection.length})</span>
                  </button>
                )}
                <button onClick={() => setPickerOpen(false)} className="w-10 h-10 flex items-center justify-center bg-white/5 hover:bg-red-500/20 rounded-xl text-white transition-colors">
                  <span className="material-symbols-outlined">close</span>
                </button>
              </div>
            </div>
            <div className="p-4 border-b border-white/5 bg-black/20 flex flex-col gap-3">
              <div className="relative">
                <span className="material-symbols-outlined absolute left-4 top-1/2 -translate-y-1/2 text-slate-400">search</span>
                <input
                  type="text"
                  placeholder={`Search ${allItemsList.length} items...`}
                  value={searchQuery}
                  onChange={e => setSearchQuery(e.target.value)}
                  className="w-full bg-slate-900 border border-white/10 rounded-xl py-4 pl-12 pr-4 text-white placeholder-slate-500 focus:outline-none focus:border-purple-500 focus:ring-1 focus:ring-purple-500 transition-all font-bold"
                />
              </div>
              <div className="flex flex-wrap gap-2">
                {CATEGORIES.map(cat => (
                  <button
                    key={cat.id}
                    onClick={() => setActiveCategory(cat.id)}
                    className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-sm font-bold transition-all ${
                      activeCategory === cat.id
                        ? 'bg-purple-500/20 border-purple-500/50 text-purple-300'
                        : 'bg-white/5 border-white/5 text-slate-400 hover:bg-white/10 hover:text-white'
                    }`}
                  >
                    <span className="material-symbols-outlined text-[16px]">{cat.icon}</span>
                    <span>{cat.label}</span>
                  </button>
                ))}
              </div>
            </div>
            <div className="flex-1 overflow-y-auto p-4 grid grid-cols-3 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-8 gap-3">
              {isLoadingItems && (
                <div className="col-span-full flex flex-col items-center justify-center py-16 text-slate-400">
                  <span className="material-symbols-outlined text-5xl animate-spin mb-3">progress_activity</span>
                  <span className="text-sm font-bold tracking-widest">LOADING ITEMS...</span>
                </div>
              )}
              {filteredItems.map(item => {
                const isBlueprint = item.category === 'Blueprint';
                const rarityColor = getRarityHex(item.rarity);
                const isSelected = tempSelection.some(i => i.id === item.id);
                return (
                  <button 
                    key={item.id} 
                    onClick={() => handleSelectItem(item)} 
                    className="bg-slate-800/50 rounded-xl p-2 flex flex-col items-center transition-all duration-200 group relative"
                    style={{ 
                      ...(isBlueprint ? {
                        backgroundImage: "linear-gradient(rgba(10, 22, 40, 0.6), rgba(10, 22, 40, 0.6)), url('/images/BG-blueprint-bg.webp')", 
                        backgroundSize: 'cover', 
                        backgroundPosition: 'center',
                      } : {}),
                      border: `3px solid ${rarityColor}60`,
                      boxShadow: `0 0 10px ${rarityColor}20, inset 0 0 10px ${rarityColor}10`,
                    }}
                    onMouseEnter={(e) => {
                      e.currentTarget.style.border = `4px solid ${rarityColor}`;
                      e.currentTarget.style.boxShadow = `0 0 25px ${rarityColor}60, inset 0 0 20px ${rarityColor}30`;
                      e.currentTarget.style.transform = 'scale(1.03) translateY(-2px)';
                      e.currentTarget.style.zIndex = '10';
                      e.currentTarget.style.backgroundColor = 'rgba(30, 41, 59, 0.8)';
                    }}
                    onMouseLeave={(e) => {
                      e.currentTarget.style.border = `3px solid ${rarityColor}60`;
                      e.currentTarget.style.boxShadow = `0 0 10px ${rarityColor}20, inset 0 0 10px ${rarityColor}10`;
                      e.currentTarget.style.transform = 'scale(1) translateY(0)';
                      e.currentTarget.style.zIndex = '1';
                      e.currentTarget.style.backgroundColor = '';
                    }}
                  >
                    {/* Inner glow specifically behind the image on hover */}
                    <div className="absolute inset-0 rounded-xl opacity-0 group-hover:opacity-100 transition-opacity duration-300 pointer-events-none" style={{ background: `radial-gradient(circle at center, ${rarityColor}30 0%, transparent 70%)` }} />
                    
                    {/* Selected state overlay */}
                    {isSelected && (
                      <div className="absolute inset-0 bg-purple-500/10 border-2 border-purple-400 rounded-xl z-20 pointer-events-none">
                        <span className="material-symbols-outlined text-[20px] text-white absolute top-1.5 right-1.5 drop-shadow-[0_0_5px_rgba(0,0,0,1)] bg-purple-600 rounded-full">check_circle</span>
                      </div>
                    )}
                    
                    <div className="w-12 h-12 mb-2 relative z-10">
                      {item.image ? (
                        <img loading="lazy" src={item.image} alt={item.name} className="w-full h-full object-contain group-hover:scale-110 transition-transform duration-300 drop-shadow-[0_0_8px_rgba(0,0,0,0.5)]" />
                      ) : (
                        <SmartItemIcon itemName={item.name} rarity={item.rarity} loading="lazy" imageClassName="w-full h-full object-contain group-hover:scale-110 transition-transform duration-300 drop-shadow-[0_0_8px_rgba(0,0,0,0.5)]" iconClassName="text-3xl text-slate-600" />
                      )}
                    </div>
                    <div className="text-[9px] font-black text-center text-slate-300 uppercase line-clamp-2 w-full break-words relative z-10 text-shadow-sm">
                      {item.name}
                    </div>
                  </button>
                );
              })}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default TradeScreen;
