export const translations: Record<string, Record<string, string>> = {
  en: {
    // BottomNav
    "nav.home": "HOME",
    "nav.weapons": "WEAPONS",
    "nav.mods": "MODS",
    "nav.materials": "MATERIALS",
    "nav.equipments": "EQUIPMENTS",
    "nav.blueprints": "BLUEPRINTS",
    "nav.trade": "TRADE",
    "nav.planner": "PLANNER",

    // Home
    "home.title": "SCRAPPY HUB",
    "home.weapons": "Weapons",
    "home.mods": "Mods",
    "home.materials": "Materials",
    "home.equipments": "Equipments",
    "home.blueprints": "Blueprints",
    "home.trade": "Trade",
    "home.stash_planner": "STASH PLANNER",
    "home.stash_desc": "Build your setup and calculate the exact materials needed.",

    // General
    "rarity.common": "COMMON",
    "rarity.uncommon": "UNCOMMON",
    "rarity.rare": "RARE",
    "rarity.epic": "EPIC",
    "rarity.legendary": "LEGENDARY",
    "action.back": "Back",
    "action.close": "Close",

    // Tooltips
    "tooltip.compatible_weapons": "COMPATIBLE WEAPONS",
    "tooltip.bonus_stats": "BONUS STATS",
    "tooltip.requirements": "REQUIREMENTS",
    "tooltip.backpack_slots": "BACKPACK SLOTS",
    "tooltip.max_weight": "MAX WEIGHT",
    "tooltip.weight_capacity": "WEIGHT CAPACITY",
    "tooltip.tier": "TIER",
    "tooltip.rarity": "RARITY",
    "tooltip.stack_size": "STACK SIZE",
    "tooltip.celeste_seeds": "CELESTE SEEDS",
    "tooltip.purchasable": "PURCHASABLE FROM CELESTE",
    "tooltip.craftable": "CRAFTABLE",
    "tooltip.salvageable": "SALVAGEABLE",
    "tooltip.used_in": "USED IN",
    "tooltip.source": "SOURCE",
    "tooltip.crafting": "CRAFTING",
    "tooltip.recycling": "RECYCLING",
    "tooltip.salvaging": "SALVAGING",
    "tooltip.weight": "WEIGHT",
    "tooltip.backpack": "BACKPACK",
    "tooltip.quick_use": "QUICK USE",
    "tooltip.safe_pocket": "SAFE POCKET",
    "tooltip.shield_compat": "SHIELD COMPATIBILITY",
    "tooltip.perks": "PERKS",
    "tooltip.press_shift": "Press [SHIFT] to Lock & Inspect",
    "tooltip.inspection_locked": "Inspection Locked",
    "tooltip.scroll_more": "Scroll to view more details",
    "tooltip.move_mouse": "Move mouse away to close",
    "tooltip.scroll_apply": "Scroll to explore / Click to apply",

    // Blueprints Screen
    "blueprints.title": "BLUEPRINTS",
    "blueprints.owned": "OWNED",
    "blueprints.missing": "MISSING",
    "blueprints.all": "ALL",
    "blueprints.search_placeholder": "Search blueprints...",
    "blueprints.no_blueprints": "No blueprints found",
    "blueprints.export_title": "SHARE YOUR PROGRESS",
    "blueprints.export_desc": "Generate a beautiful image overlay summarizing your owned and missing blueprints.",
    "blueprints.btn_export": "EXPORT",
    "blueprints.btn_download": "SAVE IMAGE",
    "blueprints.btn_copy": "COPY AS LINK",
    "blueprints.btn_copied": "COPIED!",
    "blueprints.btn_share": "SHARE",
    "blueprints.share_desc": "WhatsApp, Discord...",
    "blueprints.download_desc": "Download as .jpg",
    "blueprints.toast.copied": "Image copied! Paste into WhatsApp Web, Discord, etc.",
    "blueprints.toast.saved": "Image saved - share it manually.",
    "blueprints.empty.title": "NO BLUEPRINTS HERE",
    "blueprints.empty.desc_owned": "Click on the cards below to mark as owned.",
    "blueprints.empty.desc_missing": "Everything marked as owned!",
    "blueprints.export.title.owned": "BLUEPRINTS I ALREADY HAVE",
    "blueprints.export.title.missing": "BLUEPRINTS I STILL NEED",
    "blueprints.export.title.all": "ALL MY BLUEPRINTS",
    "blueprints.export.desc.owned": "These are the blueprints in my collection.",
    "blueprints.export.desc.missing": "I don't have these blueprints yet.",
    "blueprints.export.desc.all": "Full blueprint collection overview.",
    "blueprints.export.generated_by": "GENERATED BY SCRAPPY HUB • ARC RAIDERS",
    "blueprints.btn_select_all": "SELECT ALL",
    "blueprints.btn_clear_all": "CLEAR ALL",
    "blueprints.generating": "GENERATING...",

    // Trade Screen
    "trade.title": "TRADE",
    "trade.intent.wtb": "SEEKING",
    "trade.intent.wts": "OFFERING",
    "trade.intent.have": "HAVE",
    "trade.export.have": "HAVE",
    "trade.give": "OFFERING",
    "trade.receive": "SEEKING",
    "trade.btn_select_give": "SELECT ITEM TO TRADE",
    "trade.btn_select_receive": "SELECT ITEM TO REQUEST",
    "trade.empty_give": "Add items you want to trade",
    "trade.empty_receive": "Add items you are looking for",
    "trade.btn_generate": "GENERATE CARD",
    "trade.btn_generating": "GENERATING...",
    "trade.modal_title_give": "SELECT ITEM TO TRADE",
    "trade.modal_title_receive": "SELECT ITEM TO REQUEST",
    "trade.search_items": "Search items...",
    "trade.confirm": "Confirm",
    "trade.btn_back": "Back",
    "trade.loading_assets": "Loading assets...",
    "trade.export.looking_for": "SEEKING",
    "trade.export.offering": "OFFERING",
    "trade.items_listed": "Items Listed",
    "trade.item_listed": "Item Listed",
    "trade.btn_add": "ADD",
    "trade.empty_list": "List is empty",
    "trade.btn_copy_image": "COPY IMAGE",
    "trade.copy_desc": "Paste in Discord",
    "trade.btn_save_image": "SAVE IMAGE",
    "trade.save_desc": "Download .jpg",
    "trade.build_offer": "BUILD YOUR OFFER",
    "trade.generate_offer": "GENERATE OFFER",
    "trade.generating": "GENERATING...",
    "trade.search_placeholder_prefix": "Search",
    "trade.search_placeholder_suffix": "items...",

    // Planner Screen
    "planner.title": "STASH PLANNER",
    "planner.subtitle": "Plan your loadout materials",
    "planner.tab_setup": "SETUP LOADOUT",
    "planner.tab_mats": "NEEDED MATERIALS",
    "planner.weapons_section": "WEAPONS",
    "planner.mods_section": "MODS",
    "planner.tacticals_section": "EQUIPMENT & TACTICALS",
    "planner.btn_clear": "RESET SETUP",
    "planner.btn_final_report": "GENERATE PLAN REPORT",
    "planner.report_title": "FINAL STASH PLAN",
    "planner.report_summary": "SUMMARY",
    "planner.report_total_materials": "TOTAL MATERIALS NEEDED",
    "planner.report_no_materials": "No materials needed. Add items in Setup to plan your stash!",
    "planner.owned_stash": "IN STASH",
    "planner.missing_stash": "MISSING",
    "planner.add_weapon": "ADD WEAPON",
    "planner.add_mod": "ADD MOD",
    "planner.add_tactical": "ADD EQUIPMENT",
    "planner.empty_slot": "Empty Slot",
    "planner.confirm.wipe_all_title": "Wipe All Data",
    "planner.confirm.wipe_all_msg": "This will clear all primary/secondary slots, mods, and tactical items across ALL loadouts. This action cannot be undone.",
    "planner.confirm.wipe_loadout_title": "Wipe Loadout",
    "planner.confirm.wipe_loadout_msg": "Are you sure you want to clear all slots for this loadout? Other loadouts will remain untouched.",
    "planner.confirm.sys_required": "System Confirmation Required",
    "planner.confirm.cancel": "Cancel",
    "planner.confirm.confirm": "Confirm",
    "planner.picker.select_weapon": "Select Weapon",
    "planner.picker.equip_mods": "Equip Weapon Mods",
    "planner.picker.equip_augments": "Equip Augments",
    "planner.picker.equip_shields": "Equip Shields",
    "planner.picker.manage_utility": "Manage Utility Cache",
    "planner.picker.items_selected": "ITEMS SELECTED",
    "planner.picker.available_inventory": "Available Inventory",
    "planner.picker.no_items": "No items available.",
    "planner.manager_title": "Loadouts Manager",
    "planner.btn_wipe_all": "Wipe All",
    "planner.active_config": "Active Config",
    "planner.btn_wipe_loadout": "Wipe Loadout",
    "planner.rename_placeholder": "Rename",
    "planner.primary_weapon": "Primary Weapon",
    "planner.secondary_weapon": "Secondary Weapon",
    "planner.apply_mods": "Apply Mods",
    "planner.btn_edit": "EDIT",
    "planner.no_attachments": "No attachments equipped",
    "planner.no_augments": "No augments equipped",
    "planner.no_shields": "No shields equipped",
    "planner.no_tactical": "No tactical gear selected",
    "planner.stash_list": "Stash List",
    "planner.configure_loadouts_prompt": "Configure loadouts to visualize resource needs",
    "planner.items_needed_for_plan": "ITEMS NEEDED FOR PLAN",
    "planner.btn_finalize_plan": "Finalize Plan",
    "planner.btn_add_prefix": "ADD",
    "planner.btn_edit_prefix": "EDIT",
    "planner.save_load": "Save / Load",
    "planner.export_tooltip": "Export Config to File",
    "planner.import_tooltip": "Import Config from File",
    "planner.import_error": "Error importing file. Invalid format.",
    "planner.report.vital_resources": "VITAL RESOURCES",
    "planner.report.vital_resources_desc": "High-Quantity Priority Assets",
    "planner.report.planned_materials": "PLANNED MATERIALS",
    "planner.report.assets_logged": "ASSETS LOGGED",
    "planner.report.return_to_planner": "Return to Planner",
    "planner.report.authenticated_data": "Authenticated Provisioning Data",
    "planner.report.calibration_complete": "v1.4.2 // Calibration Complete",
    "category.grenades": "GRENADES",
    "category.shields": "SHIELDS",
    "category.healing": "HEALING",
    "category.utility": "UTILITY",
    "category.augments": "AUGMENTS",
    "category.muzzle": "Muzzle",
    "category.magazine": "Magazine",
    "category.underbarrel": "Underbarrel",
    "category.stock": "Stock",
    "category.special": "Special",
    "category.optics": "Optics",
    "category.tech": "Tech",
    "weapon_type.ar": "AR",
    "weapon_type.smg": "SMG",
    "weapon_type.shotgun": "SHOTGUN",
    "weapon_type.sniper": "SNIPER",
    "weapon_type.lmg": "LMG",
    "weapon_type.pistol": "PISTOL",
    "weapon_type.launcher": "LAUNCHER",
    "materials.trader_celeste": "Trader Celeste",

    // Overlays / Details
    "overlay.salvage": "SALVAGE VALUE",
    "overlay.craft": "CRAFTING RECIPE",
    "overlay.recycle": "RECYCLING COST",
    "overlay.none": "None",
    "overlay.crafted_at": "CRAFTED AT",
    "overlay.source": "OBTAINED BY",
    "overlay.source.world": "World Loot / Salvage",
    "overlay.source.celeste": "Celeste Trader",
    "overlay.source.craft": "Crafting Station",
    "overlay.not_craftable": "NOT CRAFTABLE",
    "overlay.tier_system": "TIER SYSTEM",
    "overlay.weapon_system": "WEAPON SYSTEM · 1.0",
    "overlay.mod_system": "MOD SYSTEM · 2.0",
    "overlay.tactical_system": "TACTICAL SYSTEM · 3.0",
    "overlay.best_setups": "BEST SETUPS (PvP)",
    "overlay.tier": "TIER",
    "overlay.from_tier": "FROM TIER",
    "overlay.to_tier": "TO TIER",
    "overlay.repair_tiers": "REPAIR TIERS",
    "overlay.durability": "DURABILITY",
    "overlay.upgrades": "UPGRADES",
    "overlay.crafting_cost": "CRAFTING COST",
    "overlay.material_archive": "MATERIAL ARCHIVE",
    "overlay.used_in": "USED IN",
    "overlay.station": "Station",
    "overlay.equipment": "EQUIPMENT",
    "overlay.perks": "PERKS",
    "stat.weight": "WEIGHT",
    "stat.backpack": "BACKPACK",
    "stat.quick_use": "QUICK USE",
    "stat.safe_pocket": "SAFE POCKET",
    "stat.shield_compat": "SHIELD COMPATIBILITY",
    "hint.lock_tooltip": "💡 Tip: Hover over any item and press [SHIFT] to lock the details panel."
  },
  "pt-BR": {
    // BottomNav
    "nav.home": "INÍCIO",
    "nav.weapons": "ARMAS",
    "nav.mods": "MODS",
    "nav.materials": "MATERIAIS",
    "nav.equipments": "EQUIPAMENTOS",
    "nav.blueprints": "PROJETOS",
    "nav.trade": "TROCAS",
    "nav.planner": "PLANEJADOR",

    // Home
    "home.title": "SCRAPPY HUB",
    "home.weapons": "Armas",
    "home.mods": "Mods",
    "home.materials": "Materiais",
    "home.equipments": "Equipamentos",
    "home.blueprints": "Projetos",
    "home.trade": "Trocas",
    "home.stash_planner": "PLANEJADOR",
    "home.stash_desc": "Monte seu arsenal e calcule os materiais exatos necessários.",

    // General
    "rarity.common": "COMUM",
    "rarity.uncommon": "INCOMUM",
    "rarity.rare": "RARO",
    "rarity.epic": "ÉPICO",
    "rarity.legendary": "LENDÁRIO",
    "action.back": "Voltar",
    "action.close": "Fechar",

    // Tooltips
    "tooltip.compatible_weapons": "ARMAS COMPATÍVEIS",
    "tooltip.bonus_stats": "ATRIBUTOS DE BÔNUS",
    "tooltip.requirements": "REQUISITOS",
    "tooltip.backpack_slots": "ESPAÇO NA MOCHILA",
    "tooltip.max_weight": "PESO MÁXIMO",
    "tooltip.weight_capacity": "CAPACIDADE DE PESO",
    "tooltip.tier": "NÍVEL (TIER)",
    "tooltip.rarity": "RARIDADE",
    "tooltip.stack_size": "TAMANHO DO PENTE / ACÚMULO",
    "tooltip.celeste_seeds": "SEMENTES CELESTE",
    "tooltip.purchasable": "COMPRÁVEL NA CELESTE",
    "tooltip.craftable": "FABRICÁVEL",
    "tooltip.salvageable": "RECUPERÁVEL",
    "tooltip.used_in": "USADO EM",
    "tooltip.source": "COMO OBTER",
    "tooltip.crafting": "CRIAÇÃO",
    "tooltip.recycling": "RECICLAGEM",
    "tooltip.salvaging": "DESMONTE",
    "tooltip.weight": "PESO",
    "tooltip.backpack": "MOCHILA",
    "tooltip.quick_use": "USO RÁPIDO",
    "tooltip.safe_pocket": "BOLSO SEGURO",
    "tooltip.shield_compat": "COMPATIBILIDADE DE ESCUDO",
    "tooltip.perks": "VANTAGENS",
    "tooltip.press_shift": "Pressione [SHIFT] para Travar & Inspecionar",
    "tooltip.inspection_locked": "Inspeção Travada",
    "tooltip.scroll_more": "Role para ver mais detalhes",
    "tooltip.move_mouse": "Afaste o mouse para fechar",
    "tooltip.scroll_apply": "Role para explorar / Clique para aplicar",

    // Blueprints Screen
    "blueprints.title": "PROJETOS",
    "blueprints.owned": "OBTIDOS",
    "blueprints.missing": "FALTANDO",
    "blueprints.all": "TODOS",
    "blueprints.search_placeholder": "Buscar projetos...",
    "blueprints.no_blueprints": "Nenhum projeto encontrado",
    "blueprints.export_title": "COMPARTILHE SEU PROGRESSO",
    "blueprints.export_desc": "Gere uma imagem personalizada resumindo seus projetos obtidos e pendentes.",
    "blueprints.btn_export": "EXPORTAR",
    "blueprints.btn_download": "SALVAR IMAGEM",
    "blueprints.btn_copy": "COPIAR LINK",
    "blueprints.btn_copied": "COPIADO!",
    "blueprints.btn_share": "COMPARTILHAR",
    "blueprints.share_desc": "WhatsApp, Discord...",
    "blueprints.download_desc": "Baixar como .jpg",
    "blueprints.toast.copied": "Imagem copiada! Cole no WhatsApp Web, Discord, etc.",
    "blueprints.toast.saved": "Imagem salva - compartilhe manualmente.",
    "blueprints.empty.title": "NENHUM PROJETO AQUI",
    "blueprints.empty.desc_owned": "Clique nos cartões abaixo para marcar como obtido.",
    "blueprints.empty.desc_missing": "Tudo marcado como obtido!",
    "blueprints.export.title.owned": "PROJETOS QUE JÁ POSSUO",
    "blueprints.export.title.missing": "PROJETOS QUE AINDA PRECISO",
    "blueprints.export.title.all": "TODOS OS MEUS PROJETOS",
    "blueprints.export.desc.owned": "Estes são os projetos na minha coleção.",
    "blueprints.export.desc.missing": "Eu ainda não tenho esses projetos.",
    "blueprints.export.desc.all": "Visão geral completa da coleção de projetos.",
    "blueprints.export.generated_by": "GERADO PELO SCRAPPY HUB • ARC RAIDERS",
    "blueprints.btn_select_all": "SELECIONAR TODOS",
    "blueprints.btn_clear_all": "LIMPAR TODOS",
    "blueprints.generating": "GERANDO...",

    // Trade Screen
    "trade.title": "TROCAS",
    "trade.intent.wtb": "PROCURO:",
    "trade.intent.wts": "TROCO POR:",
    "trade.intent.have": "TENHO:",
    "trade.export.have": "TENHO:",
    "trade.give": "TROCO POR:",
    "trade.receive": "PROCURO:",
    "trade.btn_select_give": "SELECIONAR ITEM PARA OFERECER",
    "trade.btn_select_receive": "SELECIONAR ITEM PARA PEDIR",
    "trade.empty_give": "Adicione itens que deseja negociar",
    "trade.empty_receive": "Adicione itens que você procura",
    "trade.btn_generate": "GERAR CARD DE TROCA",
    "trade.btn_generating": "GERANDO CARD...",
    "trade.modal_title_give": "SELECIONAR ITEM PARA NEGOCIAR",
    "trade.modal_title_receive": "SELECIONAR ITEM PARA PEDIR",
    "trade.search_items": "Buscar itens...",
    "trade.confirm": "Confirmar",
    "trade.btn_back": "Voltar",
    "trade.loading_assets": "Carregando arquivos...",
    "trade.export.looking_for": "PROCURO:",
    "trade.export.offering": "TROCO POR:",
    "trade.items_listed": "Itens Listados",
    "trade.item_listed": "Item Listado",
    "trade.btn_add": "ADICIONAR",
    "trade.empty_list": "A lista está vazia",
    "trade.btn_copy_image": "COPIAR IMAGEM",
    "trade.copy_desc": "Cole no Discord",
    "trade.btn_save_image": "SALVAR IMAGEM",
    "trade.save_desc": "Baixar .jpg",
    "trade.build_offer": "CRIE SUA OFERTA",
    "trade.generate_offer": "GERAR OFERTA",
    "trade.generating": "GERANDO...",
    "trade.search_placeholder_prefix": "Buscar",
    "trade.search_placeholder_suffix": "itens...",

    // Planner Screen
    "planner.title": "PLANEJADOR",
    "planner.subtitle": "Planeje os materiais de seu inventário",
    "planner.tab_setup": "CONFIGURAR ARSENAL",
    "planner.tab_mats": "MATERIAIS NECESSÁRIOS",
    "planner.weapons_section": "ARMAS",
    "planner.mods_section": "MODS (ANEXOS)",
    "planner.tacticals_section": "EQUIPAMENTOS E TÁTICOS",
    "planner.btn_clear": "RESETAR CONFIGURAÇÃO",
    "planner.btn_final_report": "GERAR RELATÓRIO DO PLANO",
    "planner.report_title": "PLANO DE STASH FINAL",
    "planner.report_summary": "RESUMO",
    "planner.report_total_materials": "TOTAL DE MATERIAIS NECESSÁRIOS",
    "planner.report_no_materials": "Nenhum material necessário. Adicione itens na aba Configurar para planejar seu stash!",
    "planner.owned_stash": "NO STASH",
    "planner.missing_stash": "FALTANDO",
    "planner.add_weapon": "ADICIONAR ARMA",
    "planner.add_mod": "ADICIONAR MOD",
    "planner.add_tactical": "ADICIONAR EQUIPAMENTO",
    "planner.empty_slot": "Espaço Vazio",
    "planner.confirm.wipe_all_title": "Limpar Todos os Dados",
    "planner.confirm.wipe_all_msg": "Isso limpará todas as armas primárias/secundárias, mods e itens táticos em TODOS os arsenais. Esta ação não pode ser desfeita.",
    "planner.confirm.wipe_loadout_title": "Limpar Arsenal",
    "planner.confirm.wipe_loadout_msg": "Tem certeza que deseja limpar todos os espaços deste arsenal? Outros arsenais não serão afetados.",
    "planner.confirm.sys_required": "Confirmação do Sistema Necessária",
    "planner.confirm.cancel": "Cancelar",
    "planner.confirm.confirm": "Confirmar",
    "planner.picker.select_weapon": "Selecionar Arma",
    "planner.picker.equip_mods": "Equipar Mods de Arma",
    "planner.picker.equip_augments": "Equipar Acessórios (Augments)",
    "planner.picker.equip_shields": "Equipar Escudos",
    "planner.picker.manage_utility": "Gerenciar Utilitários",
    "planner.picker.items_selected": "ITENS SELECIONADOS",
    "planner.picker.available_inventory": "Inventário Disponível",
    "planner.picker.no_items": "Nenhum item disponível.",
    "planner.manager_title": "Gerenciador de Arsenais",
    "planner.btn_wipe_all": "Limpar Tudo",
    "planner.active_config": "Config Ativa",
    "planner.btn_wipe_loadout": "Limpar Arsenal",
    "planner.rename_placeholder": "Renomear",
    "planner.primary_weapon": "Arma Primária",
    "planner.secondary_weapon": "Arma Secundária",
    "planner.apply_mods": "Aplicar Mods",
    "planner.btn_edit": "EDITAR",
    "planner.no_attachments": "Nenhum mod equipado",
    "planner.no_augments": "Nenhum acessório equipado",
    "planner.no_shields": "Nenhum escudo equipado",
    "planner.no_tactical": "Nenhum item tático selecionado",
    "planner.stash_list": "Lista do Stash",
    "planner.configure_loadouts_prompt": "Configure seus arsenais para visualizar os recursos necessários",
    "planner.items_needed_for_plan": "ITENS NECESSÁRIOS PARA O PLANO",
    "planner.btn_finalize_plan": "Finalizar Plano",
    "planner.btn_add_prefix": "ADD",
    "planner.btn_edit_prefix": "EDITAR",
    "planner.save_load": "Salvar / Carregar",
    "planner.export_tooltip": "Exportar Configuração para Arquivo",
    "planner.import_tooltip": "Importar Configuração de Arquivo",
    "planner.import_error": "Erro ao importar arquivo. Formato inválido.",
    "planner.report.vital_resources": "RECURSOS VITAIS",
    "planner.report.vital_resources_desc": "Recursos Prioritários de Alta Quantidade",
    "planner.report.planned_materials": "MATERIAIS PLANEJADOS",
    "planner.report.assets_logged": "RECURSOS REGISTRADOS",
    "planner.report.return_to_planner": "Retornar ao Planejador",
    "planner.report.authenticated_data": "Dados de Provisionamento Autenticados",
    "planner.report.calibration_complete": "v1.4.2 // Calibração Concluída",
    "category.grenades": "GRANADAS",
    "category.shields": "ESCUDOS",
    "category.healing": "CURA",
    "category.utility": "UTILITÁRIOS",
    "category.augments": "ACESSÓRIOS",
    "category.muzzle": "Boca",
    "category.magazine": "Carregador",
    "category.underbarrel": "Acoplamento",
    "category.stock": "Coronha",
    "category.special": "Especial",
    "category.optics": "Mira",
    "category.tech": "Tecnologia",
    "weapon_type.ar": "Fuzil de Assalto (AR)",
    "weapon_type.smg": "Submetralhadora (SMG)",
    "weapon_type.shotgun": "Escopeta (Shotgun)",
    "weapon_type.sniper": "Rifle de Precisão (Sniper)",
    "weapon_type.lmg": "Metralhadora Leve (LMG)",
    "weapon_type.pistol": "Pistola",
    "weapon_type.launcher": "Lançador",
    "materials.trader_celeste": "Comerciante Celeste",

    // Overlays / Details
    "overlay.salvage": "VALOR DE DESMONTE",
    "overlay.craft": "RECEITA DE CRIAÇÃO",
    "overlay.recycle": "CUSTO DE RECICLAGEM",
    "overlay.none": "Nenhum",
    "overlay.crafted_at": "FABRICADO EM",
    "overlay.source": "COMO OBTER",
    "overlay.source.world": "Saque no Mundo / Desmonte",
    "overlay.source.celeste": "Comerciante Celeste",
    "overlay.source.craft": "Estação de Criação",
    "overlay.not_craftable": "NÃO FABRICÁVEL",
    "overlay.tier_system": "SISTEMA DE TIER",
    "overlay.weapon_system": "SISTEMA DE ARMAS · 1.0",
    "overlay.mod_system": "SISTEMA DE MODS · 2.0",
    "overlay.tactical_system": "SISTEMA TÁTICO · 3.0",
    "overlay.best_setups": "MELHORES SETUPS (PvP)",
    "overlay.tier": "TIER",
    "overlay.from_tier": "DO TIER",
    "overlay.to_tier": "PARA O TIER",
    "overlay.repair_tiers": "NÍVEIS DE REPARO",
    "overlay.durability": "DURABILIDADE",
    "overlay.upgrades": "MELHORIAS",
    "overlay.crafting_cost": "CUSTO DE CRIAÇÃO",
    "overlay.material_archive": "ARQUIVO DE MATERIAL",
    "overlay.used_in": "USADO EM",
    "overlay.station": "Estação",
    "overlay.equipment": "EQUIPAMENTO",
    "overlay.perks": "VANTAGENS",
    "stat.weight": "PESO",
    "stat.backpack": "MOCHILA",
    "stat.quick_use": "USO RÁPIDO",
    "stat.safe_pocket": "BOLSO SEGURO",
    "stat.shield_compat": "COMPATIBILIDADE DE ESCUDO",
    "hint.lock_tooltip": "💡 Dica: Posicione o cursor sobre qualquer item e pressione [SHIFT] para fixar o painel de detalhes."
  }
};

export const itemTranslations: Record<string, { name: string; description: string; perks?: string }> = {
  "Metal Parts": {
    name: "Partes Metálicas",
    description: "Componente de metal básico usado em quase todas as criações do Scrappy."
  },
  "Rubber Parts": {
    name: "Partes de Borracha",
    description: "Pedaços flexíveis de borracha salvos de detritos industriais."
  },
  "Plastic Parts": {
    name: "Partes Plásticas",
    description: "Fragmentos de polímero duráveis limpos de contêineres e eletrodomésticos antigos."
  },
  "Fabric": {
    name: "Tecido",
    description: "Retalhos de pano bruto cruciais para fazer bandagens e tecer coletes táticos."
  },
  "Steel Spring": {
    name: "Mola de Aço",
    description: "Uma bobina de aço resiliente de alta tensão, vital para peças de armas e amortecedores."
  },
  "Wires": {
    name: "Fios",
    description: "Fios condutores de cobre encapados, cruciais para ligar componentes elétricos."
  },
  "Duct Tape": {
    name: "Fita Adesiva",
    description: "Fita adesiva reforçada de nível militar. Une o mundo scrap inteiro."
  },
  "Assorted Seeds": {
    name: "Sementes Sortidas",
    description: "Sementes de flora selvagem que podem ser plantadas ou negociadas."
  },
  "Chemicals": {
    name: "Produtos Químicos",
    description: "Substâncias químicas reativas salvas de laboratórios e plantas industriais."
  },
  "Oil": {
    name: "Óleo",
    description: "Lubrificante viscoso escuro para engrenagens mecânicas e explosivos incendiários."
  },
  "Simple Gun Parts": {
    name: "Partes Simples de Armas",
    description: "Gatilhos brutos, canos e molas usados na manufatura de armas básicas."
  },
  "Light Gun Parts": {
    name: "Partes Leves de Armas",
    description: "Componentes usinados de precisão otimizados para armas automáticas leves e pistolas."
  },
  "Medium Gun Parts": {
    name: "Partes Médias de Armas",
    description: "Receptores robustos e canos balanceados usados em rifles de assalto."
  },
  "Heavy Gun Parts": {
    name: "Partes Pesadas de Armas",
    description: "Componentes reforçados de aço capazes de suportar o impacto de metralhadoras e snipers pesadas."
  },
  "Advanced Mechanical Components": {
    name: "Componentes Mecânicos Avançados",
    description: "Engrenagens e mancais de liga leve com tolerâncias micrométricas para engenharia avançada."
  },
  "Mechanical Components": {
    name: "Componentes Mecânicos",
    description: "Pistões e engrenagens recuperados de maquinários arruinados."
  },
  "Mod Components": {
    name: "Componentes de Mods",
    description: "Kits de encaixe especializados para trilhos táticos e miras de armas."
  },
  "Magnet": {
    name: "Ímã",
    description: "Ímã ferromagnético forte comumente usado em sensores e aceleradores magnéticos."
  },
  "ARC Alloy": {
    name: "Liga ARC",
    description: "Metal refinado exótico com propriedades condutoras anômalas, colhido de destroços de ARC."
  },
  "Advanced ARC Powercell": {
    name: "Célula de Energia ARC Avançada",
    description: "Uma fonte de energia ARC de alta capacidade e extremamente estável, usada nos armamentos mais letais."
  },
  "ARC Powercell": {
    name: "Célula de Energia ARC",
    description: "A fonte de alimentação básica que energiza a tecnologia robótica ARC."
  },
  "Electrical Components": {
    name: "Componentes Elétricos",
    description: "Placas de circuito integradas e fusíveis recuperados de computadores."
  },
  "Advanced Electrical Components": {
    name: "Componentes Elétricos Avançados",
    description: "Microprocessadores militares blindados contra pulsos eletromagnéticos."
  },
  "ARC Circuitry": {
    name: "Circuitos ARC",
    description: "Fiação e chips biossintéticos complexos que processam os algoritmos de combate dos robôs ARC."
  },
  "ARC Motion Core": {
    name: "Núcleo de Movimento ARC",
    description: "Mecanismo giroscópico antigravitacional que estabiliza robôs ARC de alto nível."
  },
  "Antiseptic": {
    name: "Antisséptico",
    description: "Álcool cirúrgico e compostos desinfetantes para purificar feridas."
  },
  "Canister": {
    name: "Recipiente",
    description: "Vasilha de plástico reforçado ou metal capaz de conter fluidos pressurizados."
  },
  "Tick Pod": {
    name: "Casulo Tick",
    description: "Bolsa orgânica intacta de um drone Tick. Produz compostos químicos sob pressão."
  },
  "Durable Cloth": {
    name: "Pano Durável",
    description: "Pano grosso de nylon balístico, perfeito para mochilas e reforço de armaduras."
  },
  "Great Mullein": {
    name: "Verbasco",
    description: "Uma planta medicinal local usada em curativos fitoterápicos."
  },
  "Moss": {
    name: "Musgo",
    description: "Musgo de caverna úmido com propriedades coagulantes naturais."
  },
  "Battery": {
    name: "Bateria",
    description: "Bateria de íon-lítio recarregável padrão para pequenos eletrônicos."
  },
  "Power Rod": {
    name: "Bastão de Energia",
    description: "Núcleo gerador de microfusão usado para alimentar dispositivos portáteis de alta demanda."
  },
  "Syringe": {
    name: "Seringa",
    description: "Seringa de nível médico com agulha de aço inoxidável."
  },
  "Voltage Converter": {
    name: "Conversor de Voltagem",
    description: "Dispositivo que regula a voltagem para evitar que circuitos sensíveis queimem."
  },
  "Complex Gun Parts": {
    name: "Partes Complexas de Armas",
    description: "Mecanismos de ferrolho e câmaras de precisão para rifles de alta cadência."
  },
  "Magnetic Accelerator": {
    name: "Acelerador Magnético",
    description: "Bobinas eletromagnéticas usadas para arremessar projéteis a velocidades hipersônicas."
  },
  "Processor": {
    name: "Processador",
    description: "Unidade central de processamento recuperada de tecnologia civil de alto nível."
  },
  "Exodus Modules": {
    name: "Módulos Exodus",
    description: "Dispositivos encriptados contendo esquemas coloniais da antiga corporação Exodus."
  },
  "Crude Explosives": {
    name: "Explosivos Brutos",
    description: "Uma mistura instável de pólvora e compostos caseiros."
  },
  "Explosive Compound": {
    name: "Composto Explosivo",
    description: "Explosivo plástico estável e refinado de alta velocidade de detonação."
  },
  "Synthesized Fuel": {
    name: "Combustível Sintetizado",
    description: "Combustível químico refinado ideal para lança-chamas ou motores scrap."
  },
  "Firefly Burner": {
    name: "Queimador Firefly",
    description: "Componente de plasma térmico extraído de drones Firefly da ARC."
  },
  "Rocketeer Driver": {
    name: "Propulsor Rocketeer",
    description: "Turbina de exaustão de alta velocidade recuperada de unidades voadoras ARC."
  },
  "Comet Igniter": {
    name: "Ignitor Comet",
    description: "Dispositivo piezoelétrico de alta ignição térmica de ligas especiais."
  },
  "Light Shield": {
    name: "Escudo Leve",
    description: "Escudo tático de fibra leve para defesa de emergência rápida."
  },
  "Medium Shield": {
    name: "Escudo Médio",
    description: "Escudo balístico padrão com boa absorção de impacto."
  },
  "Heavy Shield": {
    name: "Escudo Pesado",
    description: "Escudo maciço reforçado com placas de liga ARC para resistência extrema."
  },
  "Rope": {
    name: "Corda",
    description: "Corda de fibra trançada ultra resistente para rapel e amarração."
  },
  "Sensors": {
    name: "Sensores",
    description: "Lentes infravermelhas e detectores de movimento miniaturizados."
  },
  "Speaker Component": {
    name: "Componente de Alto-falante",
    description: "Transdutor eletroacústico para amplificação de áudio e frequências."
  },
  "Hornet Driver": {
    name: "Propulsor Hornet",
    description: "Micromotores e hélices de empuxo vetorial de drones Hornet da ARC."
  },
  "Matriarch Reactor": {
    name: "Reator Matriarca",
    description: "Núcleo termonuclear complexo extraído das temíveis máquinas Matriarch."
  },
  "Queen Reactor": {
    name: "Reator Rainha",
    description: "Reator de fusão exótica superestabilizado de classe superior colhido das máquinas ARC Queen."
  },
  "Light Impact Grenade": {
    name: "Granada de Impacto Leve",
    description: "Dispositivo explosivo ágil que detona imediatamente ao colidir com qualquer superfície."
  },
  "Smoke Grenade": {
    name: "Granada de Fumaça",
    description: "Cria uma espessa cortina de fumaça cinzenta para ocultar movimentos ou forçar recuos."
  },
  "Showstopper": {
    name: "Paratudo",
    description: "Dispositivo PEM portátil que desativa temporariamente escudos e robôs próximos."
  },
  "Jolt Mine": {
    name: "Mina de Choque",
    description: "Mina terrestre de proximidade que emite uma descarga elétrica incapacitante em área."
  },
  "Explosive Mine": {
    name: "Mina Explosiva",
    description: "Mina de proximidade tradicional de alto dano destrutivo a blindagens robóticas."
  },
  "Snap Blast Grenade": {
    name: "Granada de Detonação Instantânea",
    description: "Pequeno explosivo magnético ágil que se prende a alvos metálicos antes de detonar."
  },
  "Heavy Fuze Grenade": {
    name: "Granada de Fusível Pesado",
    description: "Granada de fragmentação pesada com fusível de 4 segundos. Enorme raio de detonação."
  },
  "Blaze Grenade": {
    name: "Granada Incendiária",
    description: "Espalha combustível em chamas pela área de impacto, causando dano contínuo de queima."
  },
  "Trailblazer": {
    name: "Desbravador",
    description: "Arremessa um sinalizador de longo alcance que revela inimigos em tempo real através das paredes."
  },
  "Wolfpack": {
    name: "Matilha",
    description: "Dispositivo tático que libera uma salva de mini-mísseis teleguiados em direção a alvos múltiplos."
  },
  "Seeker Grenade": {
    name: "Granada Rastreadora",
    description: "Granada inteligente autopropulsada que busca e persegue ativamente o inimigo mais próximo."
  },
  "Shrapnel Grenade": {
    name: "Granada de Estilhaços",
    description: "Explode disparando centenas de pregos e estilhaços cortantes. Causa sangramento massivo."
  },
  "Deadline": {
    name: "Prazo Final",
    description: "Gera uma barreira de lasers de alta energia. Causa dano severo a qualquer máquina que a cruzar."
  },
  "Shield Recharger": {
    name: "Recarregador de Escudo",
    description: "Dispositivo de suporte que projeta um campo de indução para reabastecer escudos táticos aliados."
  },
  "Surge Shield Recharger": {
    name: "Recarregador de Escudo de Sobrecarga",
    description: "Supercarrega temporariamente o escudo dos aliados além de sua capacidade nominal."
  },
  "Vita Spray": {
    name: "Vita Spray",
    description: "Aerossol médico portátil que cura pequenos cortes e ferimentos leves em área."
  },
  "Vita Shot": {
    name: "Vita Shot",
    description: "Injeção de adrenalina e compostos restauradores para cura instantânea rápida."
  },
  "Sterilized Bandage": {
    name: "Bandagem Esterilizada",
    description: "Bandagem básica tratada com antisséptico para parar sangramentos rapidamente."
  },
  "Herbal Bandage": {
    name: "Bandagem Herbal",
    description: "Bandagem natural de ervas que promove regeneração de vida gradual a longo prazo."
  },
  "Defibrillator": {
    name: "Desfibrilador",
    description: "Dispositivo de reanimação de emergência rápida para levantar aliados caídos no campo."
  },
  "Compensator I": {
    name: "Compensador I",
    description: "Controle de Recuo Vertical Aumentado"
  },
  "Compensator II": {
    name: "Compensador II",
    description: "Controle de Recuo Vertical Altamente Aumentado, Velocidade de Mira Reduzida"
  },
  "Compensator III": {
    name: "Compensador III",
    description: "Controle de Recuo Vertical Máximo, Velocidade de Mira Reduzida"
  },
  "Muzzle Brake I": {
    name: "Freio de Boca I",
    description: "Controle de Recuo Horizontal Aumentado"
  },
  "Muzzle Brake II": {
    name: "Freio de Boca II",
    description: "Controle de Recuo Horizontal Altamente Aumentado, Velocidade de Mira Reduzida"
  },
  "Muzzle Brake III": {
    name: "Freio de Boca III",
    description: "Controle de Recuo Horizontal Máximo, Velocidade de Mira Reduzida"
  },
  "Shotgun Choke I": {
    name: "Estrangulador de Escopeta I",
    description: "Dispersão de Chumbo Reduzida"
  },
  "Shotgun Choke II": {
    name: "Estrangulador de Escopeta II",
    description: "Dispersão de Chumbo Altamente Reduzida, Cadência de Tiro Reduzida"
  },
  "Shotgun Choke III": {
    name: "Estrangulador de Escopeta III",
    description: "Dispersão de Chumbo Mínima, Cadência de Tiro Reduzida"
  },
  "Silencer I": {
    name: "Silenciador I",
    description: "Geração de Ameaça Reduzida, Ruído da Arma Abafado"
  },
  "Silencer II": {
    name: "Silenciador II",
    description: "Geração de Ameaça Altamente Reduzida, Ruído Abafado, Velocidade do Projétil Reduzida"
  },
  "Silencer III": {
    name: "Silenciador III",
    description: "Supressão de Ameaça Máxima, Ruído Abafado, Velocidade do Projétil Reduzida"
  },
  "Extended Barrel": {
    name: "Cano Estendido",
    description: "Alcance de Dano Aumentado, Velocidade do Projétil Aumentada"
  },
  "Extended Light Mag I": {
    name: "Carregador Leve Estendido I",
    description: "Capacidade do Carregador Aumentada"
  },
  "Extended Light Mag II": {
    name: "Carregador Leve Estendido II",
    description: "Capacidade do Carregador Altamente Aumentada, Tempo de Recarga Aumentado"
  },
  "Extended Light Mag III": {
    name: "Carregador Leve Estendido III",
    description: "Capacidade do Carregador Máxima, Tempo de Recarga Aumentado"
  },
  "Extended Medium Mag I": {
    name: "Carregador Médio Estendido I",
    description: "Capacidade do Carregador Aumentada"
  },
  "Extended Medium Mag II": {
    name: "Carregador Médio Estendido II",
    description: "Capacidade do Carregador Altamente Aumentada, Tempo de Recarga Aumentado"
  },
  "Extended Medium Mag III": {
    name: "Carregador Médio Estendido III",
    description: "Capacidade do Carregador Máxima, Tempo de Recarga Aumentado"
  },
  "Extended Shotgun Mag I": {
    name: "Carregador de Escopeta Estendido I",
    description: "Capacidade de Cartuchos Aumentada"
  },
  "Extended Shotgun Mag II": {
    name: "Carregador de Escopeta Estendido II",
    description: "Capacidade de Cartuchos Altamente Aumentada, Tempo de Recarga Aumentado"
  },
  "Extended Shotgun Mag III": {
    name: "Carregador de Escopeta Estendido III",
    description: "Capacidade de Cartuchos Máxima, Tempo de Recarga Aumentado"
  },
  "Angled Grip I": {
    name: "Empunhadura Angular I",
    description: "Velocidade de Mira (ADS) Aumentada"
  },
  "Angled Grip II": {
    name: "Empunhadura Angular II",
    description: "Velocidade de Mira Altamente Aumentada, Estabilidade de Oscilação Reduzida"
  },
  "Angled Grip III": {
    name: "Empunhadura Angular III",
    description: "Velocidade de Mira Máxima, Estabilidade de Oscilação Reduzida"
  },
  "Vertical Grip I": {
    name: "Empunhadura Vertical I",
    description: "Tempo de Recuperação de Recuo Reduzido"
  },
  "Vertical Grip II": {
    name: "Empunhadura Vertical II",
    description: "Tempo de Recuperação de Recuo Altamente Reduzido, Velocidade de Movimento ao Mirar Reduzida"
  },
  "Vertical Grip III": {
    name: "Empunhadura Vertical III",
    description: "Tempo de Recuperação de Recuo Mínimo, Velocidade de Movimento ao Mirar Reduzida"
  },
  "Horizontal Grip": {
    name: "Empunhadura Horizontal",
    description: "Estabilidade de Tiro Livre Aumentada, Velocidade de Movimento ao Mirar Aumentada"
  },
  "Stable Stock I": {
    name: "Coronha Estável I",
    description: "Estabilidade de Oscilação ao Mirar Aumentada"
  },
  "Stable Stock II": {
    name: "Coronha Estável II",
    description: "Estabilidade de Oscilação Altamente Aumentada, Tempo de Equipar Aumentado"
  },
  "Stable Stock III": {
    name: "Coronha Estável III",
    description: "Estabilidade de Oscilação Máxima, Tempo de Equipar Aumentado"
  },
  "Lightweight Stock": {
    name: "Coronha Leve",
    description: "Velocidade de Movimento ao Mirar Aumentada, Tempo de Desequipar Aumentado"
  },
  "Kinetic Converter": {
    name: "Conversor Cinético",
    description: "Converte a Força de Recuo da Arma em Micro-regeneração de Escudo ao Atingir"
  },
  "Anvil Splitter": {
    name: "Divisor Anvil",
    description: "Converte Munição Padrão em Fragmentos de Projétil que Destroem Blindagem"
  },
  "Rattler": {
    name: "Cascavel",
    description: "Pistola semiautomática ágil e de alta precisão. Excelente como arma secundária confiável."
  },
  "Arpeggio": {
    name: "Arpejo",
    description: "Pistola de rajada compacta e de disparo rápido, ideal para encontros de curta distância."
  },
  "Tempest": {
    name: "Tempestade",
    description: "Submetralhadora leve com altíssima cadência de tiro, destruidora de alvos próximos."
  },
  "Bettina": {
    name: "Bettina",
    description: "Lança-granadas tático de precisão. Dispara projéteis explosivos em arco."
  },
  "Bobcat": {
    name: "Lince",
    description: "Rifle de assalto versátil com excelente controle de recuo e cadência balanceada."
  },
  "Vulcano": {
    name: "Vulcano",
    description: "Metralhadora leve pesada com enorme capacidade de munição para fogo de supressão."
  },
  "Hairpin": {
    name: "Grampo",
    description: "Pistola de pregos de alta pressão, silenciosa e mortal."
  },
  "Hullcracker": {
    name: "Quebra-Casco",
    description: "Escopeta de cano duplo clássica de alto impacto a curtíssima distância."
  },
  "Ferro": {
    name: "Ferro",
    description: "Revólver pesado de calibre massivo. Cada disparo causa dano devastador."
  },
  "Stitcher": {
    name: "Costureira",
    description: "Rifle de precisão semiautomático projetado para engajamentos de médio a longo alcance."
  },
  "Kettle": {
    name: "Chaleira",
    description: "Lança-chamas caseiro devastador que incinera hordas de robôs ARC."
  },
  "Il Toro": {
    name: "Il Toro",
    description: "Rifle de precisão de ferrolho potente, capaz de perfurar blindagens pesadas."
  },
  "Anvil": {
    name: "Bigorna",
    description: "Rifle de assalto pesado de calibre robusto com tiros lentos de alto impacto."
  },
  "Burletta": {
    name: "Burletta",
    description: "Escopeta automática devastadora para combate frenético em área."
  },
  "Renegade": {
    name: "Renegado",
    description: "Rifle tático de precisão com modo de disparo alternado ágil."
  },
  "Venator": {
    name: "Venator",
    description: "Rifle eletromagnético experimental que dispara flechettes energizadas de alta velocidade."
  },
  "Osprey": {
    name: "Águia-Pesqueira",
    description: "Rifle de rajada de precisão tático, balanceado para todas as distâncias."
  },
  "Torrente": {
    name: "Torrente",
    description: "Metralhadora rotativa leve de alta tecnologia. Requer aquecimento antes de disparar."
  },
  "Canto": {
    name: "Canto",
    description: "Lança-foguetes devastador de longo alcance. Destruição garantida."
  },
  "Dolabra": {
    name: "Dolabra",
    description: "Dispositivo de combate de proximidade com lâmina vibratória de alta frequência."
  },
  "Shredder Gyro": {
    name: "Shredder Gyro",
    description: "Mecanismo rotativo giroscópico tático para disparos de fragmentação."
  },
  "Vaporizer Regulator": {
    name: "Vaporizer Regulator",
    description: "Módulo regulador de plasma térmico para dispersão em cone de calor extremo."
  },
  "Trigger 'Nade": {
    name: "Granada de Gatilho",
    description: "Granada leve de ativação manual imediata sob sinal de rádio."
  },
  "Trigger Nade": {
    name: "Granada de Impacto Manual",
    description: "Granada acionada à distância por um gatilho de rádio tático."
  },
  "Gas Grenade": {
    name: "Granada de Gás",
    description: "Libera uma cortina tóxica densa e altamente corrosiva em área."
  },
  "Lure Grenade": {
    name: "Granada Chamariz",
    description: "Projeta hologramas sonoros que enganam sensores de IA e atraem inimigos robóticos."
  },
  "Gas Mine": {
    name: "Mina de Gás",
    description: "Dispositivo de pressão defensivo que explode cobrindo a área com névoa corrosiva."
  },
  "Pulse Mine": {
    name: "Mina de Pulso",
    description: "Cria um campo desacelerador intermitente que sabota a mobilidade mecânica ARC."
  },
  "Bandage": {
    name: "Bandagem",
    description: "Bandagem de pano simples para curativo de emergência rápido."
  },
  "Adrenaline Shot": {
    name: "Injeção de Adrenalina",
    description: "Estimulante sintético militar que acelera o metabolismo e regenera vida."
  },
  "Barricade Kit": {
    name: "Kit de Barricada",
    description: "Barreira tática compacta para proteção imediata contra fogo inimigo no campo."
  },
  "Tactical Mk. 3 (Revival)": {
    name: "Tático Mk. 3 (Reanimação)",
    description: "Módulo de suporte avançado que melhora drasticamente a velocidade de reanimação de aliados.",
    perks: "Velocidade de reanimação aumentada em 50% e concede escudo temporário ao aliado reanimado."
  },
  "Combat Mk. 1": {
    name: "Combate Mk. 1",
    description: "Armadura de combate básica para proteção inicial.",
    perks: "Suporta Escudo Leve, aumento moderado na resistência a danos mecânicos."
  },
  "Looting Mk. 1": {
    name: "Coleta Mk. 1",
    description: "Módulo utilitário leve projetado para aumentar a eficiência de coleta.",
    perks: "+10% de velocidade de corrida ao carregar sacos pesados e +2 espaços de mochila."
  },
  "Tactical Mk. 1": {
    name: "Tático Mk. 1",
    description: "Módulo tático básico que fornece suporte de utilidade básico no campo.",
    perks: "+1 espaço de Quick Use e recarga 10% mais rápida de habilidades utilitárias."
  },
  "Combat Mk. 3 (Aggressive)": {
    name: "Combate Mk. 3 (Agressivo)",
    description: "Construído para assalto na linha de frente. Alta integridade de escudo e otimizado para implantação de recursos ofensivos.",
    perks: "+2 espaços de granada e regeneração de 2 HP a cada 5 s (pausa por 30 s ao sofrer dano)."
  },
  "Combat Mk.3 (Aggressive)": {
    name: "Combate Mk. 3 (Agressivo)",
    description: "Construído para assalto na linha de frente. Alta integridade de escudo e otimizado para implantação de recursos ofensivos.",
    perks: "+2 espaços de granada e regeneração de 2 HP a cada 5 s (pausa por 30 s ao sofrer dano)."
  },
  "Combat Mk. 3 (Flanking)": {
    name: "Combate Mk. 3 (Flanqueador)",
    description: "Otimizado para mobilidade ofensiva de flanco e ataques de surpresa devastadores.",
    perks: "+15% de velocidade de movimento ao correr e +20% de dano pelas costas do inimigo."
  },
  "Looting Mk. 2": {
    name: "Coleta Mk. 2",
    description: "Módulo utilitário intermediário que aumenta significativamente a capacidade de transporte e velocidade de saque.",
    perks: "+15% de velocidade de saque, +4 espaços de mochila e +10kg de capacidade de peso máximo."
  },
  "Looting Mk. 3 (Cautious)": {
    name: "Coleta Mk. 3 (Cauteloso)",
    description: "Projetado para sobrevivência furtiva de saqueadores solitários.",
    perks: "Passos silenciosos a 50% de distância, raio de detecção de inimigos reduzido no minimapa."
  },
  "Looting Mk. 3 (Safekeeper)": {
    name: "Coleta Mk. 3 (Guardião)",
    description: "Garante proteção máxima para os saques mais preciosos obtidos nas incursões.",
    perks: "O Bolso Seguro aceita qualquer tipo de item (incluindo armas) protegendo-os de perda na morte."
  },
  "Looting MK. 3 (Safekeeper)": {
    name: "Coleta Mk. 3 (Guardião)",
    description: "Garante proteção máxima para os saques mais preciosos obtidos nas incursões.",
    perks: "O Bolso Seguro aceita qualquer tipo de item (incluindo armas) protegendo-os de perda na morte."
  },
  "Looting Mk. 3 (Survivor)": {
    name: "Coleta Mk. 3 (Sobrevivente)",
    description: "Focado em expedições de longa duração em condições ambientais severas.",
    perks: "+25kg de peso máximo de carga e +5 espaços de mochila para transporte massivo."
  },
  "Looting MK. 3 (Survivor)": {
    name: "Coleta Mk. 3 (Sobrevivente)",
    description: "Focado em expedições de longa duração em condições ambientais severas.",
    perks: "+25kg de peso máximo de carga e +5 espaços de mochila para transporte massivo."
  },
  "Tactical Mk. 2": {
    name: "Tático Mk. 2",
    description: "Módulo de suporte avançado que aprimora o uso de utilitários e táticos de médio escalão.",
    perks: "+2 slots de utilitários rápidos e redução de 20% no cooldown de todos os arremessáveis."
  },
  "Tactical Mk. 3 (Defensive)": {
    name: "Tático Mk. 3 (Defensivo)",
    description: "Módulo de engenharia militar voltado para fortificação defensiva imediata.",
    perks: "+1 slot de utilitários rápidos e cortina de fumaça automática de emergência ao quebrar o escudo."
  },
  "Tactical MK.3 (Defensive)": {
    name: "Tático Mk. 3 (Defensivo)",
    description: "Módulo de engenharia militar voltado para fortificação defensiva imediata.",
    perks: "+1 slot de utilitários rápidos e cortina de fumaça automática de emergência ao quebrar o escudo."
  },
  "Tactical Mk. 3 (Healing)": {
    name: "Tático Mk. 3 (Cura)",
    description: "O melhor suporte médico do Scrappy Hub. Campo biótico de cura aprimorado.",
    perks: "+3 slots de cura rápida e cria uma nuvem de cura em área (~20 HP em 10 s) ao reanimar um parceiro."
  },
  "Tactical MK.3 (Healing)": {
    name: "Tático Mk. 3 (Cura)",
    description: "O melhor suporte médico do Scrappy Hub. Campo biótico de cura aprimorado.",
    perks: "+3 slots de cura rápida e cria uma nuvem de cura em área (~20 HP em 10 s) ao reanimar um parceiro."
  },
  "Combat Mk. 2": {
    name: "Combate Mk. 2",
    description: "Módulo militar robusto para proteção intermediária em batalhas intensas contra robôs.",
    perks: "Suporta Escudo Médio, concede +15% de integridade máxima de escudos táticos equipados."
  },
  "Shotgun Silencer": {
    name: "Silenciador de Escopeta",
    description: "Supressão acústica e dispersão de gases para disparos de escopeta discretos."
  },
  "Red Light Stick": {
    name: "Bastão de Luz Vermelha",
    description: "Sinalizador brilhante vermelho usado para demarcar pontos ou distrair."
  },
  "Tagging Grenade": {
    name: "Granada de Marcação",
    description: "Libera sensores de eco para rastrear inimigos através de superfícies."
  },
  "Crash Mat": {
    name: "Amortecedor de Quedas",
    description: "Colchão de ar de alta absorção de impacto contra quedas extremas."
  },
  "Tactical MK.3 (Smoke)": {
    name: "Tático MK.3 (Fumaça)",
    description: "Módulo especializado em ocultação térmica e fumaça em larga escala."
  },
  "White Flag": {
    name: "Bandeira Branca",
    description: "Dispositivo simbólico que reduz a hostilidade de IAs próximas temporariamente."
  },
  "Remote Raider Flare": {
    name: "Sinalizador Raider Remoto",
    description: "Dispositivo de iluminação tática disparado à distância."
  },
  "Aphelion": {
    name: "Afélio",
    description: "Projeto do lendário rifle eletromagnético militar de precisão extrema."
  },
  "Powered Descender": {
    name: "Descensor Motorizado",
    description: "Equipamento motorizado de alta velocidade para cabos e rapel tático."
  },
  "Trailblazer": {
    name: "Desbravador",
    description: "Dispositivo sinalizador de rastreamento com varredura persistente."
  },
  "Green Light Stick": {
    name: "Bastão de Luz Verde",
    description: "Sinalizador de luz fria verde de alta duração."
  },
  "Padded Stock": {
    name: "Coronha Acolchoada",
    description: "Melhora o conforto físico e reduz a oscilação da mira sob fogo intenso."
  },
  "Fireworks Box": {
    name: "Caixa de Fogos de Artifício",
    description: "Mistura pirotécnica improvisada para sinalização ou distração caótica."
  },
  "Yellow Light Stick": {
    name: "Bastão de Luz Amarela",
    description: "Sinalizador de visibilidade amarela para condições de névoa densa."
  },
  "Surge Coil": {
    name: "Bobina de Sobrecarga",
    description: "Dispositivo de indução eletromagnética para sobrecarga ativa de escudos."
  },
  "Blue Light Stick": {
    name: "Bastão de Luz Azul",
    description: "Sinalizador de luz azul de alta visibilidade subaquática e noturna."
  },
  "Adv Mechanical Components": {
    name: "Componentes Mecânicos Avançados",
    description: "Engrenagens e pistões usinados a laser para engenharia de alta performance."
  },
  "Adv ARC Powercell": {
    name: "Célula de Energia ARC Avançada",
    description: "Núcleo gerador de fusão fria de classe superior de robôs ARC."
  },
  "Adv Electrical Components": {
    name: "Componentes Elétricos Avançados",
    description: "Microprocessadores blindados contra radiação e pulsos eletromagnéticos."
  },
  "Padded Stock III": {
    name: "Coronha Acolchoada III",
    description: "Estabilização balística máxima, minimizando totalmente a oscilação."
  },
  "Aphelion": {
    name: "Afélio",
    description: "Rifle eletromagnético lendário de alta tecnologia e precisão avassaladora."
  },
  "Jupiter": {
    name: "Júpiter",
    description: "Fuzil de assalto pesado experimental de alta cadência e dano cinético extremo."
  },
  "Equalizer": {
    name: "Equalizador",
    description: "Canhão de mão de alta precisão com projéteis explosivos de liga exótica."
  },
  "Zipline": {
    name: "Tirolesa",
    description: "Mecanismo portátil de ancoragem rápida para deslocamento vertical por cabos."
  },
  "Damaged Leaper Pulse Unit": {
    name: "Unidade de Pulso Leaper Danificada",
    description: "Núcleo de locomoção quebrado de drones saltadores Leaper da ARC."
  },
  "Damaged Rocketeer Driver": {
    name: "Propulsor Rocketeer Danificado",
    description: "Módulo propulsor queimado de unidades voadoras da ARC."
  },
  "Bastion Cell": {
    name: "Célula Bastion",
    description: "Bateria protetora de alta indução obtida de robôs blindados ARC."
  },
  "Bombardier Cell": {
    name: "Célula Bombardier",
    description: "Fonte de ignição química estável colhida de unidades de artilharia da ARC."
  },
  "Leaper Pulse Unit": {
    name: "Unidade de Pulso Leaper",
    description: "Núcleo de pulso intacto de drones Leaper. Usado em tecnologia magnética."
  },
  "Pulse Mine Blueprint": {
    name: "Projeto de Mina de Pulso",
    description: "Esquema completo para manufaturar minas eletromagnéticas."
  },
  "Soap": {
    name: "Sabonete",
    description: "Item de higiene civil precioso na colônia. Mantém a sanidade scrap."
  },
  "Bleach": {
    name: "Alvejante",
    description: "Desinfetante químico concentrado em garrafa plástica."
  },
  "Rattler II": {
    name: "Cascavel II",
    description: "Versão calibrada de Tier II da confiável pistola semiautomática."
  },
  "Rubber Pad": {
    name: "Placa de Borracha",
    description: "Borracha vulcanizada espessa de maquinários civis arruinados."
  },
  "Ruined Accordion": {
    name: "Acordeão Arruinado",
    description: "Instrumento musical destruído. Contém molas e partes de borracha."
  },
  "ARC Flex Rubber": {
    name: "Borracha Flexível ARC",
    description: "Composto sintético isolante elétrico de alta flexibilidade."
  },
  "Diving Goggles": {
    name: "Óculos de Mergulho",
    description: "Equipamento plástico protetor de olhos, antigo mas utilizável."
  },
  "Degraded ARC Rubber": {
    name: "Borracha ARC Degradada",
    description: "Borracha danificada por eletrocussão de restos robóticos."
  },
  "Deflated Football": {
    name: "Bola de Futebol Murcha",
    description: "Couro sintético flexível clássico para fabricação de tecidos."
  },
  "Expired Respirator": {
    name: "Respirador Expirado",
    description: "Máscara de gás civil antiga. Útil para partes plásticas e tecidos."
  },
  "Headphones": {
    name: "Fones de Ouvido",
    description: "Dispositivo de áudio antigo. Útil para extrair fios e borracha."
  },
  "Thermostat": {
    name: "Termostato",
    description: "Componente regulador de temperatura civil com circuitos simples."
  },
  "Ruined Riot Shield": {
    name: "Escudo Antimotim Arruinado",
    description: "Grande placa de polímero balístico quebrada, ótima para partes plásticas."
  },
  "Toaster": {
    name: "Torradeira",
    description: "Eletrodoméstico de cozinha arruinado. Cheio de fios e chapas de metal."
  },
  "ARC Synthetic Resin": {
    name: "Resina Sintética ARC",
    description: "Polímero líquido endurecido colhido de blindagens leves robóticas."
  },
  "Cooling Fan": {
    name: "Ventoinha de Resfriamento",
    description: "Ventoinha de plástico de computadores antigos, boa para fios e plástico."
  },
  "Recorder": {
    name: "Gravador",
    description: "Dispositivo de áudio portátil quebrado para saque de circuitos plásticos."
  },
  "Shaker": {
    name: "Coqueteleira",
    description: "Recipiente de metal/plástico de bar civil arruinado."
  },
  "Dried-Out ARC Resin": {
    name: "Resina ARC Ressecada",
    description: "Composto químico solidificado arruinado de alta reciclagem plástica."
  },
  "Camera Lens": {
    name: "Lente de Câmera",
    description: "Lente óptica de vidro e polímero de precis."
  },
  "Remote Control": {
    name: "Controle Remoto",
    description: "Dispositivo infravermelho civil simples. Fonte ágil de circuitos e plástico."
  },
  "Alarm Clock": {
    name: "Despertador",
    description: "Relógio mecânico antigo, cheio de engrenagens de latão e molas."
  },
  "Microscope": {
    name: "Microscópio",
    description: "Equipamento de laboratório óptico raro. Contém componentes elétricos de alta qualidade."
  },
  "Industrial Magnet": {
    name: "Ímã Industrial",
    description: "Bloco magnético robusto e pesado de alta indução ferromagnética."
  },
  "Ripped Safety Vest": {
    name: "Colete Refletivo Rasgado",
    description: "Colete de sinalização rasgado, ótimo para extrair tecidos sintéticos."
  },
  "Ruined Tactical Vest": {
    name: "Colete Tático Arruinado",
    description: "Placa balística vazia danificada com tiras de tecido militar forte."
  },
  "Rattler IV": {
    name: "Cascavel IV",
    description: "Pistola Rattler de Tier IV com máxima calibração de combate."
  },
  "Il Toro IV": {
    name: "Il Toro IV",
    description: "Sniper pesada Il Toro modificada para o nível extremo de Tier IV."
  },
  "Unusable Weapon": {
    name: "Arma Inutilizável",
    description: "Pedaço de rifle enferrujado destruído, bom apenas para reciclagem de peças."
  },
  "Trigger \"": {
    name: "Gatilho de Impacto",
    description: "Mecanismo detonador tático para minas e granadas de gatilho."
  },
  "Cooling Coil": {
    name: "Bobina de Resfriamento",
    description: "Tubo espiral de cobre para resfriamento de líquidos térmicos."
  },
  "Spring Cushion": {
    name: "Almofada de Molas",
    description: "Molas helicoidais de aço estofadas em tecido."
  },
  "Portable TV": {
    name: "TV Portátil",
    description: "Televisor antigo civil. Excelente fonte de fiação e circuitos eletrônicos."
  },
  "Acoustic Guitar": {
    name: "Violão Acústico",
    description: "Violão arruinado. As cordas de aço fornecem fios flexíveis."
  },
  "Power Cable": {
    name: "Cabo de Força",
    description: "Cabo de alimentação elétrico industrial grosso de cobre encapado."
  },
  "Damaged Heat Sink": {
    name: "Dissipador de Calor Danificado",
    description: "Placa aletada de alumínio para resfriamento passivo."
  },
  "Power Bank": {
    name: "Carregador Portátil",
    description: "Bateria recarregável civil de alta capacidade."
  },
  "Humidifier": {
    name: "Umidificador",
    description: "Aparelho de tratamento de ar civil. Fonte de fiação e plásticos."
  },
  "Broken Handheld Radio": {
    name: "Rádio de Mão Quebrado",
    description: "Walkie-talkie arruinado com fiação e circuitos simples."
  },
  "Broken Taser": {
    name: "Taser Quebrado",
    description: "Dispositivo de choque quebrado. Contém eletrodos de cobre e capacitores."
  },
  "Frequency Modulation Box": {
    name: "Caixa de Modulação de Frequência",
    description: "Módulo eletrônico de rádio militar."
  },
  "Photoelectric Cloak": {
    name: "Manto Fotoelétrico",
    description: "Módulo tático avançado que concede invisibilidade térmica contra robôs."
  },
  "Bobcat IV": {
    name: "Lince IV",
    description: "Rifle Bobcat calibrado de Tier IV de elite."
  },
  "Tempest IV": {
    name: "Tempestade IV",
    description: "Submetralhadora Tempest refinada ao nível máximo de combate."
  },
  "Bobcat III": {
    name: "Lince III",
    description: "Rifle Bobcat avançado de Tier III."
  },
  "Hullcracker IV": {
    name: "Quebra-Casco IV",
    description: "Escopeta Hullcracker de cano duplo robusta de Tier IV."
  },
  "Tempest III": {
    name: "Tempestade III",
    description: "Submetralhadora Tempest ágil de Tier III."
  },
  "Vulcano IV": {
    name: "Vulcano IV",
    description: "Metralhadora Vulcano de Tier IV para poder de fogo implacável."
  },
  "Bettina IV": {
    name: "Bettina IV",
    description: "Lança-granadas Bettina de elite calibrado para o Tier IV."
  },
  "Bobcat II": {
    name: "Lince II",
    description: "Rifle Bobcat balanceado de Tier II."
  },
  "Hullcracker III": {
    name: "Quebra-Casco III",
    description: "Escopeta Hullcracker robusta de Tier III."
  },
  "Osprey IV": {
    name: "Águia-Pesqueira IV",
    description: "Rifle Osprey de elite modificado para o Tier IV."
  },
  "Fried Motherboard": {
    name: "Placa-Mãe Queimada",
    description: "Placa de circuito arruinada cheia de transistores de silício."
  },
  "Rotary Encoder": {
    name: "Codificador Rotativo",
    description: "Sensor eletrônico de medição de rotações mecânicas."
  },
  "Sample Cleaner": {
    name: "Purificador de Amostras",
    description: "Dispositivo elétrico de purificação celular com microbombas."
  },
  "Signal Amplifier": {
    name: "Amplificador de Sinal",
    description: "Amplifica frequências de ondas de rádio em circuitos de longo alcance."
  },
  "Snitch Scanner": {
    name: "Scanner Snitch",
    description: "Módulo de radar óptico retirado de drones espiões Snitch da ARC."
  },
  "Spotter Relay": {
    name: "Relé de Reconhecimento",
    description: "Receptor de telemetria eletrônica de unidades espias ARC."
  },
  "Vulcano III": {
    name: "Vulcano III",
    description: "Metralhadora Vulcano pesada de Tier III."
  },
  "Bettina III": {
    name: "Bettina III",
    description: "Lança-granadas Bettina avançado de Tier III."
  },
  "Hullcracker II": {
    name: "Quebra-Casco II",
    description: "Escopeta Hullcracker tática de Tier II."
  },
  "Vulcano II": {
    name: "Vulcano II",
    description: "Metralhadora Vulcano robusta de Tier II."
  },
  "Bettina II": {
    name: "Bettina II",
    description: "Lança-granadas Bettina balanceado de Tier II."
  },
  "Bettina I": {
    name: "Bettina I",
    description: "Lança-granadas Bettina tático básico de Tier I."
  },
  "Bobcat I": {
    name: "Lince I",
    description: "Rifle Bobcat tático padrão de Tier I."
  },
  "Arpeggio III": {
    name: "Arpejo III",
    description: "Pistola de rajada Arpeggio calibrada para Tier III."
  },
  "Burletta IV": {
    name: "Burletta IV",
    description: "Escopeta automática Burletta de elite de Tier IV."
  },
  "Power Drill": {
    name: "Furadeira Elétrica",
    description: "Ferramenta de perfuração industrial pesada."
  },
  "Osprey III": {
    name: "Águia-Pesqueira III",
    description: "Rifle de rajada Osprey de Tier III."
  },
  "Renegade III": {
    name: "Renegado III",
    description: "Rifle de precisão Renegade tático de Tier III."
  },
  "Renegade IV": {
    name: "Renegado IV",
    description: "Rifle Renegade modificado para o Tier IV militar de elite."
  },
  "Tempest II": {
    name: "Tempestade II",
    description: "Submetralhadora Tempest calibrada para Tier II."
  },
  "Torrente III": {
    name: "Torrente III",
    description: "Metralhadora rotativa Torrente de Tier III."
  },
  "Torrente IV": {
    name: "Torrente IV",
    description: "Metralhadora rotativa Torrente calibrada ao nível máximo de Tier IV."
  },
  "Venator III": {
    name: "Caçador III",
    description: "Rifle eletromagnético Venator tático de Tier III."
  },
  "Anvil IV": {
    name: "Bigorna IV",
    description: "Rifle de assalto Anvil de Tier IV com máxima calibração de poder."
  },
  "Arpeggio IV": {
    name: "Arpejo IV",
    description: "Pistola Arpeggio modificada para o nível extremo de Tier IV."
  },
  "Anvil III": {
    name: "Bigorna III",
    description: "Rifle de assalto Anvil tático robusto de Tier III."
  },
  "Il Toro III": {
    name: "Il Toro III",
    description: "Sniper de precisão Il Toro de Tier III de alta potência."
  },
  "Anvil II": {
    name: "Bigorna II",
    description: "Rifle de assalto Anvil calibrado de Tier II."
  },
  "Jupiter (Tier 1)": {
    name: "Júpiter (Tier 1)",
    description: "Fuzil de assalto pesado Jupiter básico de Tier I."
  },
  "Aphelion (Tier 1)": {
    name: "Afélio (Tier 1)",
    description: "Rifle eletromagnético Aphelion básico de Tier I."
  },
  "Sentinel Weaponry Core": {
    name: "Núcleo de Armamento Sentinel",
    description: "Processador de combate militar exótico retirado de unidades Sentinel da ARC."
  },
  "Launcher Ammo": {
    name: "Munição de Lançador",
    description: "Granadas propelidas a foguete projetadas para lança-granadas."
  },
  "Magnetron": {
    name: "Magnetron",
    description: "Emissor de microondas eletromagnéticas térmicas de alta frequência."
  },
  "Industrial Charger": {
    name: "Carregador Industrial",
    description: "Gerador de recarga elétrica pesada de grande voltagem."
  },
  "Ion Sputter": {
    name: "Dispersor de Íons",
    description: "Gerador eletrostático exótico extraído de robôs pesados ARC."
  },
  "Fire Extinguisher": {
    name: "Extintor de Incêndio",
    description: "Recipiente pressurizado com gás CO2."
  },
  "Compressed Air Can": {
    name: "Lata de Ar Comprimido",
    description: "Lata plástica com gás pressurizado civil de limpeza."
  },
  "ARC Tick": {
    name: "ARC Tick",
    description: "Unidade robótica menor ágil da ARC que pula nos Raiders para detonar."
  },
  "ARC Tick Nymph": {
    name: "Ninfa ARC Tick",
    description: "Versão minúscula e instável dos drones Tick da ARC."
  },
  "Scavenging (Outdoors / Nature zones)": {
    name: "Coleta (Áreas Externas / Zonas Naturais)",
    description: "Recursos naturais coletados na floresta e ruínas externas."
  },
  "Scavenging (Rocks / Damp surfaces)": {
    name: "Coleta (Rochas / Superfícies Úmidas)",
    description: "Materiais orgânicos obtidos de encostas úmidas e cavernas."
  },
  "Medical Supply Box": {
    name: "Caixa de Suprimentos Médicos",
    description: "Contêiner selado civil cheio de kits médicos e químicos."
  },
  "First Aid Kit": {
    name: "Kit de Primeiros Socorros",
    description: "Estojo de resgate médico com bandagens, antissépticos e Vita Shots."
  },
  "Scavenging (Medical zones)": {
    name: "Coleta (Zonas Médicas)",
    description: "Purificação de recursos obtida em hospitais e clínicas arruinadas."
  },
  "Launcher Ammo (Incendiary)": {
    name: "Munição de Lançador (Incendiária)",
    description: "Projéteis de lançador preenchidos com Napalm sintético."
  },
  "ARC Rocketeer": {
    name: "ARC Rocketeer",
    description: "Robô de ataque aéreo móvel da ARC equipado com lança-mísseis táticos."
  },
  "ARC Bastion": {
    name: "ARC Bastion",
    description: "Robô terrestre pesado ARC projetado com gerador de escudos massivos."
  },
  "ARC Tank": {
    name: "ARC Tank",
    description: "Blindado de combate quadrúpede colossal da ARC com armamentos pesados."
  },
  "Motor": {
    name: "Motor",
    description: "Motor de indução mecânico de alto empuxo de veículos civis arruinados."
  },
  "Water Pump": {
    name: "Bomba d'Água",
    description: "Componente hidráulico civil contendo rotor e carcaça metálica."
  },
  "Turbo Pump": {
    name: "Turbobomba",
    description: "Bomba centrífuga de alta pressão para fluxo contínuo de combustível químico."
  },
  "Coolant": {
    name: "Líquido de Resfriamento",
    description: "Fluido sintético refrigerante térmico concentrado."
  },
  "Polluted Air Filter": {
    name: "Filtro de Ar Poluído",
    description: "Filtro industrial entupido de fibras sintéticas."
  },
  "Snap Hook": {
    name: "Mosquetão",
    description: "Mosquetão de liga reforçada com rolamento motorizado para cabos táticos."
  },
  "Scavenging (Residential / Commercial zones)": {
    name: "Coleta (Zonas Residenciais / Comerciais)",
    description: "Saque de componentes civis limpos de lojas e casas destruídas."
  },
  "ARC Snitch": {
    name: "ARC Snitch",
    description: "Drone espião voador ágil que varre a área para chamar reforços ARC."
  },
  "ARC Surveyor": {
    name: "ARC Surveyor",
    description: "Drone de mapeamento geográfico que vigia ruínas da colônia."
  },
  "ARC Android": {
    name: "ARC Android",
    description: "Soldado humanoide padrão de combate e patrulha militar da ARC."
  },
  "Server Rack": {
    name: "Gabinete de Servidor",
    description: "Estrutura de informática cheia de processadores e placas eletrônicas."
  },
  "Radio": {
    name: "Rádio",
    description: "Aparelho de som civil antigo com bobinas metálicas e fiação de cobre."
  },
  "Noisemaker": {
    name: "Emissor de Ruídos",
    description: "Dispositivo que emite ondas acústicas irritantes para desorientar robôs."
  },
  "ARC Hornet": {
    name: "ARC Hornet",
    description: "Microdrone voador de patrulha ágil equipado com metralhadoras térmicas."
  },
  "ARC Courier": {
    name: "ARC Courier",
    description: "Unidade robótica de transporte rápido da ARC carregando cargas valiosas."
  },
  "ARC Matriarch (Boss drop)": {
    name: "ARC Matriarch (Chefe)",
    description: "Máquina de comando titânica da ARC de alto extermínio militar."
  },
  "ARC Queen (Boss drop)": {
    name: "ARC Queen (Chefe)",
    description: "A ameaça máxima robótica aérea da ARC com reator termonuclear colossal."
  },
  "ARC Queen Leg Armor": {
    name: "Armadura da Perna da Rainha ARC",
    description: "Placa balística indestrutível obtida do chassi da colossal ARC Queen."
  }
};
