"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.itemTranslations = exports.translations = void 0;
exports.translations = {
    en: {
        // BottomNav
        "nav.home": "HOME",
        "nav.weapons": "WEAPONS",
        "nav.mods": "MODS",
        "nav.materials": "MATERIALS",
        "nav.equipments": "EQUIPMENTS",
        "nav.blueprints": "BLUEPRINTS",
        "nav.trade": "TRADE",
        "nav.planner": "PLANNER",
        // Home
        "home.title": "SCRAPPY HUB",
        "home.weapons": "Weapons",
        "home.mods": "Mods",
        "home.materials": "Materials",
        "home.equipments": "Equipments",
        "home.blueprints": "Blueprints",
        "home.trade": "Trade",
        "home.stash_planner": "STASH PLANNER",
        "home.stash_desc": "Build your setup and calculate the exact materials needed.",
        // General
        "rarity.common": "COMMON",
        "rarity.uncommon": "UNCOMMON",
        "rarity.rare": "RARE",
        "rarity.epic": "EPIC",
        "rarity.legendary": "LEGENDARY",
        "action.back": "Back",
        "action.close": "Close",
        // Tooltips
        "tooltip.compatible_weapons": "COMPATIBLE WEAPONS",
        "tooltip.bonus_stats": "BONUS STATS",
        "tooltip.requirements": "REQUIREMENTS",
        "tooltip.backpack_slots": "BACKPACK SLOTS",
        "tooltip.max_weight": "MAX WEIGHT",
        "tooltip.weight_capacity": "WEIGHT CAPACITY",
        "tooltip.tier": "TIER",
        "tooltip.rarity": "RARITY",
        "tooltip.stack_size": "STACK SIZE",
        "tooltip.celeste_seeds": "CELESTE SEEDS",
        "tooltip.purchasable": "PURCHASABLE FROM CELESTE",
        "tooltip.craftable": "CRAFTABLE",
        "tooltip.salvageable": "SALVAGEABLE",
        "tooltip.used_in": "USED IN",
        "tooltip.source": "SOURCE",
        "tooltip.crafting": "CRAFTING",
        "tooltip.recycling": "RECYCLING",
        "tooltip.salvaging": "SALVAGING",
        "tooltip.weight": "WEIGHT",
        "tooltip.backpack": "BACKPACK",
        "tooltip.quick_use": "QUICK USE",
        "tooltip.safe_pocket": "SAFE POCKET",
        "tooltip.shield_compat": "SHIELD COMPATIBILITY",
        "tooltip.perks": "PERKS",
        "tooltip.press_shift": "Press [SHIFT] to Lock & Inspect",
        "tooltip.inspection_locked": "Inspection Locked",
        "tooltip.scroll_more": "Scroll to view more details",
        "tooltip.move_mouse": "Move mouse away to close",
        // Blueprints Screen
        "blueprints.title": "BLUEPRINTS",
        "blueprints.owned": "OWNED",
        "blueprints.missing": "MISSING",
        "blueprints.all": "ALL",
        "blueprints.search_placeholder": "Search blueprints...",
        "blueprints.no_blueprints": "No blueprints found",
        "blueprints.export_title": "SHARE YOUR PROGRESS",
        "blueprints.export_desc": "Generate a beautiful image overlay summarizing your owned and missing blueprints.",
        "blueprints.btn_export": "EXPORT",
        "blueprints.btn_download": "SAVE IMAGE",
        "blueprints.btn_copy": "COPY AS LINK",
        "blueprints.btn_copied": "COPIED!",
        "blueprints.btn_share": "SHARE",
        "blueprints.share_desc": "WhatsApp, Discord...",
        "blueprints.download_desc": "Download as .jpg",
        "blueprints.toast.copied": "Image copied! Paste into WhatsApp Web, Discord, etc.",
        "blueprints.toast.saved": "Image saved - share it manually.",
        "blueprints.empty.title": "NO BLUEPRINTS HERE",
        "blueprints.empty.desc_owned": "Click on the cards below to mark as owned.",
        "blueprints.empty.desc_missing": "Everything marked as owned!",
        "blueprints.export.title.owned": "BLUEPRINTS I ALREADY HAVE",
        "blueprints.export.title.missing": "BLUEPRINTS I STILL NEED",
        "blueprints.export.title.all": "ALL MY BLUEPRINTS",
        "blueprints.export.desc.owned": "These are the blueprints in my collection.",
        "blueprints.export.desc.missing": "I don't have these blueprints yet.",
        "blueprints.export.desc.all": "Full blueprint collection overview.",
        "blueprints.export.generated_by": "GENERATED BY SCRAPPY HUB • ARC RAIDERS",
        "blueprints.btn_select_all": "SELECT ALL",
        "blueprints.btn_clear_all": "CLEAR ALL",
        "blueprints.generating": "GENERATING...",
        // Trade Screen
        "trade.title": "TRADE",
        "trade.intent.wtb": "LOOKING FOR",
        "trade.intent.wts": "TRADING",
        "trade.give": "TRADING",
        "trade.receive": "LOOKING FOR",
        "trade.btn_select_give": "SELECT ITEM TO TRADE",
        "trade.btn_select_receive": "SELECT ITEM TO REQUEST",
        "trade.empty_give": "Add items you want to trade",
        "trade.empty_receive": "Add items you are looking for",
        "trade.btn_generate": "GENERATE CARD",
        "trade.btn_generating": "GENERATING...",
        "trade.modal_title_give": "SELECT ITEM TO TRADE",
        "trade.modal_title_receive": "SELECT ITEM TO REQUEST",
        "trade.search_items": "Search items...",
        "trade.confirm": "Confirm",
        "trade.btn_back": "Back",
        "trade.loading_assets": "Loading assets...",
        "trade.export.looking_for": "I'M LOOKING FOR",
        "trade.export.offering": "I'M OFFERING",
        "trade.items_listed": "Items Listed",
        "trade.item_listed": "Item Listed",
        "trade.btn_add": "ADD",
        "trade.empty_list": "List is empty",
        "trade.btn_copy_image": "COPY IMAGE",
        "trade.copy_desc": "Paste in Discord",
        "trade.btn_save_image": "SAVE IMAGE",
        "trade.save_desc": "Download .jpg",
        "trade.build_offer": "BUILD YOUR OFFER",
        "trade.generate_offer": "GENERATE OFFER",
        "trade.generating": "GENERATING...",
        "trade.search_placeholder_prefix": "Search",
        "trade.search_placeholder_suffix": "items...",
        // Planner Screen
        "planner.title": "STASH PLANNER",
        "planner.subtitle": "Plan your loadout materials",
        "planner.tab_setup": "SETUP LOADOUT",
        "planner.tab_mats": "NEEDED MATERIALS",
        "planner.weapons_section": "WEAPONS",
        "planner.mods_section": "MODS",
        "planner.tacticals_section": "EQUIPMENT & TACTICALS",
        "planner.btn_clear": "RESET SETUP",
        "planner.btn_final_report": "GENERATE PLAN REPORT",
        "planner.report_title": "FINAL STASH PLAN",
        "planner.report_summary": "SUMMARY",
        "planner.report_total_materials": "TOTAL MATERIALS NEEDED",
        "planner.report_no_materials": "No materials needed. Add items in Setup to plan your stash!",
        "planner.owned_stash": "IN STASH",
        "planner.missing_stash": "MISSING",
        "planner.add_weapon": "ADD WEAPON",
        "planner.add_mod": "ADD MOD",
        "planner.add_tactical": "ADD EQUIPMENT",
        "planner.empty_slot": "Empty Slot",
        "planner.confirm.wipe_all_title": "Wipe All Data",
        "planner.confirm.wipe_all_msg": "This will clear all primary/secondary slots, mods, and tactical items across ALL loadouts. This action cannot be undone.",
        "planner.confirm.wipe_loadout_title": "Wipe Loadout",
        "planner.confirm.wipe_loadout_msg": "Are you sure you want to clear all slots for this loadout? Other loadouts will remain untouched.",
        "planner.confirm.sys_required": "System Confirmation Required",
        "planner.confirm.cancel": "Cancel",
        "planner.confirm.confirm": "Confirm",
        "planner.picker.select_weapon": "Select Weapon",
        "planner.picker.equip_mods": "Equip Weapon Mods",
        "planner.picker.equip_augments": "Equip Augments",
        "planner.picker.equip_shields": "Equip Shields",
        "planner.picker.manage_utility": "Manage Utility Cache",
        "planner.picker.items_selected": "ITEMS SELECTED",
        "planner.picker.available_inventory": "Available Inventory",
        "planner.picker.no_items": "No items available.",
        "planner.manager_title": "Loadouts Manager",
        "planner.btn_wipe_all": "Wipe All",
        "planner.active_config": "Active Config",
        "planner.btn_wipe_loadout": "Wipe Loadout",
        "planner.rename_placeholder": "Rename",
        "planner.primary_weapon": "Primary Weapon",
        "planner.secondary_weapon": "Secondary Weapon",
        "planner.apply_mods": "Apply Mods",
        "planner.btn_edit": "EDIT",
        "planner.no_attachments": "No attachments equipped",
        "planner.no_augments": "No augments equipped",
        "planner.no_shields": "No shields equipped",
        "planner.no_tactical": "No tactical gear selected",
        "planner.stash_list": "Stash List",
        "planner.configure_loadouts_prompt": "Configure loadouts to visualize resource needs",
        "planner.items_needed_for_plan": "ITEMS NEEDED FOR PLAN",
        "planner.btn_finalize_plan": "Finalize Plan",
        "planner.btn_add_prefix": "ADD",
        "planner.btn_edit_prefix": "EDIT",
        "planner.save_load": "Save / Load",
        "planner.export_tooltip": "Export Config to File",
        "planner.import_tooltip": "Import Config from File",
        "planner.import_error": "Error importing file. Invalid format.",
        "planner.report.vital_resources": "VITAL RESOURCES",
        "planner.report.vital_resources_desc": "High-Quantity Priority Assets",
        "planner.report.planned_materials": "PLANNED MATERIALS",
        "planner.report.assets_logged": "ASSETS LOGGED",
        "planner.report.return_to_planner": "Return to Planner",
        "planner.report.authenticated_data": "Authenticated Provisioning Data",
        "planner.report.calibration_complete": "v1.4.2 // Calibration Complete",
        "category.grenades": "GRENADES",
        "category.shields": "SHIELDS",
        "category.healing": "HEALING",
        "category.utility": "UTILITY",
        "category.augments": "AUGMENTS",
        "category.muzzle": "Muzzle",
        "category.magazine": "Magazine",
        "category.underbarrel": "Underbarrel",
        "category.stock": "Stock",
        "category.special": "Special",
        "materials.trader_celeste": "Trader Celeste",
        // Overlays / Details
        "overlay.salvage": "SALVAGE VALUE",
        "overlay.craft": "CRAFTING RECIPE",
        "overlay.recycle": "RECYCLING COST",
        "overlay.none": "None",
        "overlay.crafted_at": "CRAFTED AT",
        "overlay.source": "OBTAINED BY",
        "overlay.source.world": "World Loot / Salvage",
        "overlay.source.celeste": "Celeste Trader",
        "overlay.source.craft": "Crafting Station",
        "overlay.not_craftable": "NOT CRAFTABLE",
        "overlay.tier_system": "TIER SYSTEM",
        "overlay.weapon_system": "WEAPON SYSTEM · 1.0",
        "overlay.mod_system": "MOD SYSTEM · 2.0",
        "overlay.tactical_system": "TACTICAL SYSTEM · 3.0",
        "overlay.best_setups": "BEST SETUPS (PvP)",
        "overlay.tier": "TIER",
        "overlay.from_tier": "FROM TIER",
        "overlay.to_tier": "TO TIER",
        "overlay.repair_tiers": "REPAIR TIERS",
        "overlay.durability": "DURABILITY",
        "overlay.upgrades": "UPGRADES",
        "overlay.crafting_cost": "CRAFTING COST",
        "overlay.material_archive": "MATERIAL ARCHIVE",
        "overlay.used_in": "USED IN",
        "overlay.station": "Station",
        "overlay.equipment": "EQUIPMENT",
        "overlay.perks": "PERKS",
        "stat.weight": "WEIGHT",
        "stat.backpack": "BACKPACK",
        "stat.quick_use": "QUICK USE",
        "stat.safe_pocket": "SAFE POCKET",
        "stat.shield_compat": "SHIELD COMPATIBILITY"
    },
    "pt-BR": {
        // BottomNav
        "nav.home": "INÍCIO",
        "nav.weapons": "ARMAS",
        "nav.mods": "MODS",
        "nav.materials": "MATERIAIS",
        "nav.equipments": "EQUIPAMENTOS",
        "nav.blueprints": "PROJETOS",
        "nav.trade": "TROCAS",
        "nav.planner": "PLANEJADOR",
        // Home
        "home.title": "SCRAPPY HUB",
        "home.weapons": "Armas",
        "home.mods": "Mods",
        "home.materials": "Materiais",
        "home.equipments": "Equipamentos",
        "home.blueprints": "Projetos",
        "home.trade": "Trocas",
        "home.stash_planner": "PLANEJADOR",
        "home.stash_desc": "Monte seu arsenal e calcule os materiais exatos necessários.",
        // General
        "rarity.common": "COMUM",
        "rarity.uncommon": "INCOMUM",
        "rarity.rare": "RARO",
        "rarity.epic": "ÉPICO",
        "rarity.legendary": "LENDÁRIO",
        "action.back": "Voltar",
        "action.close": "Fechar",
        // Tooltips
        "tooltip.compatible_weapons": "ARMAS COMPATÍVEIS",
        "tooltip.bonus_stats": "ATRIBUTOS DE BÔNUS",
        "tooltip.requirements": "REQUISITOS",
        "tooltip.backpack_slots": "ESPAÇO NA MOCHILA",
        "tooltip.max_weight": "PESO MÁXIMO",
        "tooltip.weight_capacity": "CAPACIDADE DE PESO",
        "tooltip.tier": "NÍVEL (TIER)",
        "tooltip.rarity": "RARIDADE",
        "tooltip.stack_size": "TAMANHO DO PENTE / ACÚMULO",
        "tooltip.celeste_seeds": "SEMENTES CELESTE",
        "tooltip.purchasable": "COMPRÁVEL NA CELESTE",
        "tooltip.craftable": "FABRICÁVEL",
        "tooltip.salvageable": "RECUPERÁVEL",
        "tooltip.used_in": "USADO EM",
        "tooltip.source": "COMO OBTER",
        "tooltip.crafting": "CRIAÇÃO",
        "tooltip.recycling": "RECICLAGEM",
        "tooltip.salvaging": "DESMONTE",
        "tooltip.weight": "PESO",
        "tooltip.backpack": "MOCHILA",
        "tooltip.quick_use": "USO RÁPIDO",
        "tooltip.safe_pocket": "BOLSO SEGURO",
        "tooltip.shield_compat": "COMPATIBILIDADE DE ESCUDO",
        "tooltip.perks": "VANTAGENS",
        "tooltip.press_shift": "Pressione [SHIFT] para Travar & Inspecionar",
        "tooltip.inspection_locked": "Inspeção Travada",
        "tooltip.scroll_more": "Role para ver mais detalhes",
        "tooltip.move_mouse": "Afaste o mouse para fechar",
        // Blueprints Screen
        "blueprints.title": "PROJETOS",
        "blueprints.owned": "OBTIDOS",
        "blueprints.missing": "FALTANDO",
        "blueprints.all": "TODOS",
        "blueprints.search_placeholder": "Buscar projetos...",
        "blueprints.no_blueprints": "Nenhum projeto encontrado",
        "blueprints.export_title": "COMPARTILHE SEU PROGRESSO",
        "blueprints.export_desc": "Gere uma imagem personalizada resumindo seus projetos obtidos e pendentes.",
        "blueprints.btn_export": "EXPORTAR",
        "blueprints.btn_download": "SALVAR IMAGEM",
        "blueprints.btn_copy": "COPIAR LINK",
        "blueprints.btn_copied": "COPIADO!",
        "blueprints.btn_share": "COMPARTILHAR",
        "blueprints.share_desc": "WhatsApp, Discord...",
        "blueprints.download_desc": "Baixar como .jpg",
        "blueprints.toast.copied": "Imagem copiada! Cole no WhatsApp Web, Discord, etc.",
        "blueprints.toast.saved": "Imagem salva - compartilhe manualmente.",
        "blueprints.empty.title": "NENHUM PROJETO AQUI",
        "blueprints.empty.desc_owned": "Clique nos cartões abaixo para marcar como obtido.",
        "blueprints.empty.desc_missing": "Tudo marcado como obtido!",
        "blueprints.export.title.owned": "PROJETOS QUE JÁ POSSUO",
        "blueprints.export.title.missing": "PROJETOS QUE AINDA PRECISO",
        "blueprints.export.title.all": "TODOS OS MEUS PROJETOS",
        "blueprints.export.desc.owned": "Estes são os projetos na minha coleção.",
        "blueprints.export.desc.missing": "Eu ainda não tenho esses projetos.",
        "blueprints.export.desc.all": "Visão geral completa da coleção de projetos.",
        "blueprints.export.generated_by": "GERADO PELO SCRAPPY HUB • ARC RAIDERS",
        "blueprints.btn_select_all": "SELECIONAR TODOS",
        "blueprints.btn_clear_all": "LIMPAR TODOS",
        "blueprints.generating": "GERANDO...",
        // Trade Screen
        "trade.title": "TROCAS",
        "trade.intent.wtb": "PROCURO POR:",
        "trade.intent.wts": "TROCO POR:",
        "trade.give": "TROCO POR:",
        "trade.receive": "PROCURO POR:",
        "trade.btn_select_give": "SELECIONAR ITEM PARA OFERECER",
        "trade.btn_select_receive": "SELECIONAR ITEM PARA PEDIR",
        "trade.empty_give": "Adicione itens que deseja negociar",
        "trade.empty_receive": "Adicione itens que você procura",
        "trade.btn_generate": "GERAR CARD DE TROCA",
        "trade.btn_generating": "GERANDO CARD...",
        "trade.modal_title_give": "SELECIONAR ITEM PARA NEGOCIAR",
        "trade.modal_title_receive": "SELECIONAR ITEM PARA PEDIR",
        "trade.search_items": "Buscar itens...",
        "trade.confirm": "Confirmar",
        "trade.btn_back": "Voltar",
        "trade.loading_assets": "Carregando arquivos...",
        "trade.export.looking_for": "PROCURO POR:",
        "trade.export.offering": "TROCO POR:",
        "trade.items_listed": "Itens Listados",
        "trade.item_listed": "Item Listado",
        "trade.btn_add": "ADICIONAR",
        "trade.empty_list": "A lista está vazia",
        "trade.btn_copy_image": "COPIAR IMAGEM",
        "trade.copy_desc": "Cole no Discord",
        "trade.btn_save_image": "SALVAR IMAGEM",
        "trade.save_desc": "Baixar .jpg",
        "trade.build_offer": "CRIE SUA OFERTA",
        "trade.generate_offer": "GERAR OFERTA",
        "trade.generating": "GERANDO...",
        "trade.search_placeholder_prefix": "Buscar",
        "trade.search_placeholder_suffix": "itens...",
        // Planner Screen
        "planner.title": "PLANEJADOR",
        "planner.subtitle": "Planeje os materiais de seu inventário",
        "planner.tab_setup": "CONFIGURAR ARSENAL",
        "planner.tab_mats": "MATERIAIS NECESSÁRIOS",
        "planner.weapons_section": "ARMAS",
        "planner.mods_section": "MODS (ANEXOS)",
        "planner.tacticals_section": "EQUIPAMENTOS E TÁTICOS",
        "planner.btn_clear": "RESETAR CONFIGURAÇÃO",
        "planner.btn_final_report": "GERAR RELATÓRIO DO PLANO",
        "planner.report_title": "PLANO DE STASH FINAL",
        "planner.report_summary": "RESUMO",
        "planner.report_total_materials": "TOTAL DE MATERIAIS NECESSÁRIOS",
        "planner.report_no_materials": "Nenhum material necessário. Adicione itens na aba Configurar para planejar seu stash!",
        "planner.owned_stash": "NO STASH",
        "planner.missing_stash": "FALTANDO",
        "planner.add_weapon": "ADICIONAR ARMA",
        "planner.add_mod": "ADICIONAR MOD",
        "planner.add_tactical": "ADICIONAR EQUIPAMENTO",
        "planner.empty_slot": "Espaço Vazio",
        "planner.confirm.wipe_all_title": "Limpar Todos os Dados",
        "planner.confirm.wipe_all_msg": "Isso limpará todas as armas primárias/secundárias, mods e itens táticos em TODOS os arsenais. Esta ação não pode ser desfeita.",
        "planner.confirm.wipe_loadout_title": "Limpar Arsenal",
        "planner.confirm.wipe_loadout_msg": "Tem certeza que deseja limpar todos os espaços deste arsenal? Outros arsenais não serão afetados.",
        "planner.confirm.sys_required": "Confirmação do Sistema Necessária",
        "planner.confirm.cancel": "Cancelar",
        "planner.confirm.confirm": "Confirmar",
        "planner.picker.select_weapon": "Selecionar Arma",
        "planner.picker.equip_mods": "Equipar Mods de Arma",
        "planner.picker.equip_augments": "Equipar Acessórios (Augments)",
        "planner.picker.equip_shields": "Equipar Escudos",
        "planner.picker.manage_utility": "Gerenciar Utilitários",
        "planner.picker.items_selected": "ITENS SELECIONADOS",
        "planner.picker.available_inventory": "Inventário Disponível",
        "planner.picker.no_items": "Nenhum item disponível.",
        "planner.manager_title": "Gerenciador de Arsenais",
        "planner.btn_wipe_all": "Limpar Tudo",
        "planner.active_config": "Config Ativa",
        "planner.btn_wipe_loadout": "Limpar Arsenal",
        "planner.rename_placeholder": "Renomear",
        "planner.primary_weapon": "Arma Primária",
        "planner.secondary_weapon": "Arma Secundária",
        "planner.apply_mods": "Aplicar Mods",
        "planner.btn_edit": "EDITAR",
        "planner.no_attachments": "Nenhum mod equipado",
        "planner.no_augments": "Nenhum acessório equipado",
        "planner.no_shields": "Nenhum escudo equipado",
        "planner.no_tactical": "Nenhum item tático selecionado",
        "planner.stash_list": "Lista do Stash",
        "planner.configure_loadouts_prompt": "Configure seus arsenais para visualizar os recursos necessários",
        "planner.items_needed_for_plan": "ITENS NECESSÁRIOS PARA O PLANO",
        "planner.btn_finalize_plan": "Finalizar Plano",
        "planner.btn_add_prefix": "ADD",
        "planner.btn_edit_prefix": "EDITAR",
        "planner.save_load": "Salvar / Carregar",
        "planner.export_tooltip": "Exportar Configuração para Arquivo",
        "planner.import_tooltip": "Importar Configuração de Arquivo",
        "planner.import_error": "Erro ao importar arquivo. Formato inválido.",
        "planner.report.vital_resources": "RECURSOS VITAIS",
        "planner.report.vital_resources_desc": "Recursos Prioritários de Alta Quantidade",
        "planner.report.planned_materials": "MATERIAIS PLANEJADOS",
        "planner.report.assets_logged": "RECURSOS REGISTRADOS",
        "planner.report.return_to_planner": "Retornar ao Planejador",
        "planner.report.authenticated_data": "Dados de Provisionamento Autenticados",
        "planner.report.calibration_complete": "v1.4.2 // Calibração Concluída",
        "category.grenades": "GRANADAS",
        "category.shields": "ESCUDOS",
        "category.healing": "CURA",
        "category.utility": "UTILITÁRIOS",
        "category.augments": "ACESSÓRIOS",
        "category.muzzle": "Boca",
        "category.magazine": "Carregador",
        "category.underbarrel": "Acoplamento",
        "category.stock": "Coronha",
        "category.special": "Especial",
        "materials.trader_celeste": "Comerciante Celeste",
        // Overlays / Details
        "overlay.salvage": "VALOR DE DESMONTE",
        "overlay.craft": "RECEITA DE CRIAÇÃO",
        "overlay.recycle": "CUSTO DE RECICLAGEM",
        "overlay.none": "Nenhum",
        "overlay.crafted_at": "FABRICADO EM",
        "overlay.source": "COMO OBTER",
        "overlay.source.world": "Saque no Mundo / Desmonte",
        "overlay.source.celeste": "Comerciante Celeste",
        "overlay.source.craft": "Estação de Criação",
        "overlay.not_craftable": "NÃO FABRICÁVEL",
        "overlay.tier_system": "SISTEMA DE TIER",
        "overlay.weapon_system": "SISTEMA DE ARMAS · 1.0",
        "overlay.mod_system": "SISTEMA DE MODS · 2.0",
        "overlay.tactical_system": "SISTEMA TÁTICO · 3.0",
        "overlay.best_setups": "MELHORES SETUPS (PvP)",
        "overlay.tier": "TIER",
        "overlay.from_tier": "DO TIER",
        "overlay.to_tier": "PARA O TIER",
        "overlay.repair_tiers": "NÍVEIS DE REPARO",
        "overlay.durability": "DURABILIDADE",
        "overlay.upgrades": "MELHORIAS",
        "overlay.crafting_cost": "CUSTO DE CRIAÇÃO",
        "overlay.material_archive": "ARQUIVO DE MATERIAL",
        "overlay.used_in": "USADO EM",
        "overlay.station": "Estação",
        "overlay.equipment": "EQUIPAMENTO",
        "overlay.perks": "VANTAGENS",
        "stat.weight": "PESO",
        "stat.backpack": "MOCHILA",
        "stat.quick_use": "USO RÁPIDO",
        "stat.safe_pocket": "BOLSO SEGURO",
        "stat.shield_compat": "COMPATIBILIDADE DE ESCUDO"
    }
};
exports.itemTranslations = {
    // --- MATERIALS ---
    "Metal Parts": {
        name: "Partes Metálicas",
        description: "Componente de metal básico usado em quase todas as criações do Scrappy."
    },
    "Rubber Parts": {
        name: "Partes de Borracha",
        description: "Pedaços flexíveis de borracha salvos de detritos industriais."
    },
    "Plastic Parts": {
        name: "Partes Plásticas",
        description: "Fragmentos de polímero duráveis limpos de contêineres e eletrodomésticos antigos."
    },
    "Fabric": {
        name: "Tecido",
        description: "Retalhos de pano bruto cruciais para fazer bandagens e tecer coletes táticos."
    },
    "Steel Spring": {
        name: "Mola de Aço",
        description: "Uma bobina de aço resiliente de alta tensão, vital para peças de armas e amortecedores."
    },
    "Wires": {
        name: "Fios",
        description: "Fios condutores de cobre encapados, cruciais para ligar componentes elétricos."
    },
    "Duct Tape": {
        name: "Fita Adesiva",
        description: "Fita adesiva reforçada de nível militar. Une o mundo scrap inteiro."
    },
    "Assorted Seeds": {
        name: "Sementes Sortidas",
        description: "Sementes de flora selvagem que podem ser plantadas ou negociadas."
    },
    "Chemicals": {
        name: "Produtos Químicos",
        description: "Substâncias químicas reativas salvas de laboratórios e plantas industriais."
    },
    "Oil": {
        name: "Óleo",
        description: "Lubrificante viscoso escuro para engrenagens mecânicas e explosivos incendiários."
    },
    "Simple Gun Parts": {
        name: "Partes Simples de Armas",
        description: "Gatilhos brutos, canos e molas usados na manufatura de armas básicas."
    },
    "Light Gun Parts": {
        name: "Partes Leves de Armas",
        description: "Componentes usinados de precisão otimizados para armas automáticas leves e pistolas."
    },
    "Medium Gun Parts": {
        name: "Partes Médias de Armas",
        description: "Receptores robustos e canos balanceados usados em rifles de assalto."
    },
    "Heavy Gun Parts": {
        name: "Partes Pesadas de Armas",
        description: "Componentes reforçados de aço capazes de suportar o impacto de metralhadoras e snipers pesadas."
    },
    "Advanced Mechanical Components": {
        name: "Componentes Mecânicos Avançados",
        description: "Engrenagens e mancais de liga leve com tolerâncias micrométricas para engenharia avançada."
    },
    "Mechanical Components": {
        name: "Componentes Mecânicos",
        description: "Pistões e engrenagens recuperados de maquinários arruinados."
    },
    "Mod Components": {
        name: "Componentes de Mods",
        description: "Kits de encaixe especializados para trilhos táticos e miras de armas."
    },
    "Magnet": {
        name: "Ímã",
        description: "Ímã ferromagnético forte comumente usado em sensores e aceleradores magnéticos."
    },
    "ARC Alloy": {
        name: "Liga ARC",
        description: "Metal refinado exótico com propriedades condutoras anômalas, colhido de destroços de ARC."
    },
    "Advanced ARC Powercell": {
        name: "Célula de Energia ARC Avançada",
        description: "Uma fonte de energia ARC de alta capacidade e extremamente estável, usada nos armamentos mais letais."
    },
    "ARC Powercell": {
        name: "Célula de Energia ARC",
        description: "A fonte de alimentação básica que energiza a tecnologia robótica ARC."
    },
    "Electrical Components": {
        name: "Componentes Elétricos",
        description: "Placas de circuito integradas e fusíveis recuperados de computadores."
    },
    "Advanced Electrical Components": {
        name: "Componentes Elétricos Avançados",
        description: "Microprocessadores militares blindados contra pulsos eletromagnéticos."
    },
    "ARC Circuitry": {
        name: "Circuitos ARC",
        description: "Fiação e chips biossintéticos complexos que processam os algoritmos de combate dos robôs ARC."
    },
    "ARC Motion Core": {
        name: "Núcleo de Movimento ARC",
        description: "Mecanismo giroscópico antigravitacional que estabiliza robôs ARC de alto nível."
    },
    "Antiseptic": {
        name: "Antisséptico",
        description: "Álcool cirúrgico e compostos desinfetantes para purificar feridas."
    },
    "Canister": {
        name: "Recipiente",
        description: "Vasilha de plástico reforçado ou metal capaz de conter fluidos pressurizados."
    },
    "Tick Pod": {
        name: "Casulo Tick",
        description: "Bolsa orgânica intacta de um drone Tick. Produz compostos químicos sob pressão."
    },
    "Durable Cloth": {
        name: "Pano Durável",
        description: "Pano grosso de nylon balístico, perfeito para mochilas e reforço de armaduras."
    },
    "Great Mullein": {
        name: "Verbasco",
        description: "Uma planta medicinal local usada em curativos fitoterápicos."
    },
    "Moss": {
        name: "Musgo",
        description: "Musgo de caverna úmido com propriedades coagulantes naturais."
    },
    "Battery": {
        name: "Bateria",
        description: "Bateria de íon-lítio recarregável padrão para pequenos eletrônicos."
    },
    "Power Rod": {
        name: "Bastão de Energia",
        description: "Núcleo gerador de microfusão usado para alimentar dispositivos portáteis de alta demanda."
    },
    "Syringe": {
        name: "Seringa",
        description: "Seringa de nível médico com agulha de aço inoxidável."
    },
    "Voltage Converter": {
        name: "Conversor de Voltagem",
        description: "Dispositivo que regula a voltagem para evitar que circuitos sensíveis queimem."
    },
    "Complex Gun Parts": {
        name: "Partes Complexas de Armas",
        description: "Mecanismos de ferrolho e câmaras de precisão para rifles de alta cadência."
    },
    "Magnetic Accelerator": {
        name: "Acelerador Magnético",
        description: "Bobinas eletromagnéticas usadas para arremessar projéteis a velocidades hipersônicas."
    },
    "Processor": {
        name: "Processador",
        description: "Unidade central de processamento recuperada de tecnologia civil de alto nível."
    },
    "Exodus Modules": {
        name: "Módulos Exodus",
        description: "Dispositivos encriptados contendo esquemas coloniais da antiga corporação Exodus."
    },
    "Crude Explosives": {
        name: "Explosivos Brutos",
        description: "Uma mistura instável de pólvora e compostos caseiros."
    },
    "Explosive Compound": {
        name: "Composto Explosivo",
        description: "Explosivo plástico estável e refinado de alta velocidade de detonação."
    },
    "Synthesized Fuel": {
        name: "Combustível Sintetizado",
        description: "Combustível químico refinado ideal para lança-chamas ou motores scrap."
    },
    "Firefly Burner": {
        name: "Queimador Firefly",
        description: "Componente de plasma térmico extraído de drones Firefly da ARC."
    },
    "Rocketeer Driver": {
        name: "Propulsor Rocketeer",
        description: "Turbina de exaustão de alta velocidade recuperada de unidades voadoras ARC."
    },
    "Comet Igniter": {
        name: "Ignitor Comet",
        description: "Dispositivo piezoelétrico de alta ignição térmica de ligas especiais."
    },
    "Light Shield": {
        name: "Escudo Leve",
        description: "Escudo tático de fibra leve para defesa de emergência rápida."
    },
    "Medium Shield": {
        name: "Escudo Médio",
        description: "Escudo balístico padrão com boa absorção de impacto."
    },
    "Heavy Shield": {
        name: "Escudo Pesado",
        description: "Escudo maciço reforçado com placas de liga ARC para resistência extrema."
    },
    "Rope": {
        name: "Corda",
        description: "Corda de fibra trançada ultra resistente para rapel e amarração."
    },
    "Sensors": {
        name: "Sensores",
        description: "Lentes infravermelhas e detectores de movimento miniaturizados."
    },
    "Speaker Component": {
        name: "Componente de Alto-falante",
        description: "Transdutor eletroacústico para amplificação de áudio e frequências."
    },
    "Hornet Driver": {
        name: "Propulsor Hornet",
        description: "Micromotores e hélices de empuxo vetorial de drones Hornet da ARC."
    },
    "Matriarch Reactor": {
        name: "Reator Matriarca",
        description: "Núcleo termonuclear complexo extraído das temíveis máquinas Matriarch."
    },
    "Queen Reactor": {
        name: "Reator Rainha",
        description: "Reator de fusão exótica superestabilizado de classe superior colhido das máquinas ARC Queen."
    },
    // --- TACTICALS & EQUIPMENT ---
    "Light Impact Grenade": {
        name: "Granada de Impacto Leve",
        description: "Dispositivo explosivo ágil que detona imediatamente ao colidir com qualquer superfície."
    },
    "Smoke Grenade": {
        name: "Granada de Fumaça",
        description: "Cria uma espessa cortina de fumaça cinzenta para ocultar movimentos ou forçar recuos."
    },
    "Showstopper": {
        name: "Showstopper",
        description: "Dispositivo PEM portátil que desativa temporariamente escudos e robôs próximos."
    },
    "Jolt Mine": {
        name: "Mina de Choque",
        description: "Mina terrestre de proximidade que emite uma descarga elétrica incapacitante em área."
    },
    "Explosive Mine": {
        name: "Mina Explosiva",
        description: "Mina de proximidade tradicional de alto dano destrutivo a blindagens robóticas."
    },
    "Snap Blast Grenade": {
        name: "Granada de Detonação Instantânea",
        description: "Pequeno explosivo magnético ágil que se prende a alvos metálicos antes de detonar."
    },
    "Heavy Fuze Grenade": {
        name: "Granada de Fusível Pesado",
        description: "Granada de fragmentação pesada com fusível de 4 segundos. Enorme raio de detonação."
    },
    "Blaze Grenade": {
        name: "Granada Incendiária",
        description: "Espalha combustível em chamas pela área de impacto, causando dano contínuo de queima."
    },
    "Trailblazer": {
        name: "Desbravador",
        description: "Arremessa um sinalizador de longo alcance que revela inimigos em tempo real através das paredes."
    },
    "Wolfpack": {
        name: "Matilha",
        description: "Dispositivo tático que libera uma salva de mini-mísseis teleguiados em direção a alvos múltiplos."
    },
    "Seeker Grenade": {
        name: "Granada Rastreadora",
        description: "Granada inteligente autopropulsada que busca e persegue ativamente o inimigo mais próximo."
    },
    "Shrapnel Grenade": {
        name: "Granada de Estilhaços",
        description: "Explode disparando centenas de pregos e estilhaços cortantes. Causa sangramento massivo."
    },
    "Deadline": {
        name: "Linha Limite",
        description: "Gera uma barreira de lasers de alta energia. Causa dano severo a qualquer máquina que a cruzar."
    },
    "Shield Recharger": {
        name: "Recarregador de Escudo",
        description: "Dispositivo de suporte que projeta um campo de indução para reabastecer escudos táticos aliados."
    },
    "Surge Shield Recharger": {
        name: "Recarregador de Escudo de Sobrecarga",
        description: "Supercarrega temporariamente o escudo dos aliados além de sua capacidade nominal."
    },
    "Vita Spray": {
        name: "Vita Spray",
        description: "Aerossol médico portátil que cura pequenos cortes e ferimentos leves em área."
    },
    "Vita Shot": {
        name: "Vita Shot",
        description: "Injeção de adrenalina e compostos restauradores para cura instantânea rápida."
    },
    "Sterilized Bandage": {
        name: "Bandagem Esterilizada",
        description: "Bandagem básica tratada com antisséptico para parar sangramentos rapidamente."
    },
    "Herbal Bandage": {
        name: "Bandagem Herbal",
        description: "Bandagem natural de ervas que promove regeneração de vida gradual a longo prazo."
    },
    "Defibrillator": {
        name: "Desfibrilador",
        description: "Dispositivo de reanimação de emergência rápida para levantar aliados caídos no campo."
    },
    // --- MODS ---
    "Compensator I": { name: "Compensador I", description: "Increased Vertical Recoil Control" },
    "Compensator II": { name: "Compensador II", description: "Highly Increased Vertical Recoil Control, Reduced ADS Speed" },
    "Compensator III": { name: "Compensador III", description: "Maximum Vertical Recoil Control, Reduced ADS Speed" },
    "Muzzle Brake I": { name: "Freio de Boca I", description: "Increased Horizontal Recoil Control" },
    "Muzzle Brake II": { name: "Freio de Boca II", description: "Highly Increased Horizontal Recoil Control, Reduced ADS Speed" },
    "Muzzle Brake III": { name: "Freio de Boca III", description: "Maximum Horizontal Recoil Control, Reduced ADS Speed" },
    "Shotgun Choke I": { name: "Estrangulador de Escopeta I", description: "Increased Pellet Spread Tightness" },
    "Shotgun Choke II": { name: "Estrangulador de Escopeta II", description: "Highly Increased Pellet Spread Tightness, Reduced Fire Rate" },
    "Shotgun Choke III": { name: "Estrangulador de Escopeta III", description: "Maximum Pellet Spread Tightness, Reduced Fire Rate" },
    "Silencer I": { name: "Silenciador I", description: "Reduced Threat Generation, Muffled Weapon Noise" },
    "Silencer II": { name: "Silenciador II", description: "Highly Reduced Threat, Muffled Noise, Reduced Bullet Velocity" },
    "Silencer III": { name: "Silenciador III", description: "Maximum Threat Suppression, Muffled Noise, Reduced Bullet Velocity" },
    "Extended Barrel": { name: "Cano Estendido", description: "Increased Damage Range, Increased Bullet Velocity" },
    "Extended Light Mag I": { name: "Carregador Leve Estendido I", description: "Increased Magazine Capacity" },
    "Extended Light Mag II": { name: "Carregador Leve Estendido II", description: "Highly Increased Magazine Capacity, Increased Reload Time" },
    "Extended Light Mag III": { name: "Carregador Leve Estendido III", description: "Maximum Magazine Capacity, Increased Reload Time" },
    "Extended Medium Mag I": { name: "Carregador Médio Estendido I", description: "Increased Magazine Capacity" },
    "Extended Medium Mag II": { name: "Carregador Médio Estendido II", description: "Highly Increased Magazine Capacity, Increased Reload Time" },
    "Extended Medium Mag III": { name: "Carregador Médio Estendido III", description: "Maximum Magazine Capacity, Increased Reload Time" },
    "Extended Shotgun Mag I": { name: "Carregador de Escopeta Estendido I", description: "Increased Shell Capacity" },
    "Extended Shotgun Mag II": { name: "Carregador de Escopeta Estendido II", description: "Highly Increased Shell Capacity, Increased Reload Time" },
    "Extended Shotgun Mag III": { name: "Carregador de Escopeta Estendido III", description: "Maximum Shell Capacity, Increased Reload Time" },
    "Angled Grip I": { name: "Empunhadura Angular I", description: "Increased ADS Speed" },
    "Angled Grip II": { name: "Empunhadura Angular II", description: "Highly Increased ADS Speed, Reduced Sway Stability" },
    "Angled Grip III": { name: "Empunhadura Angular III", description: "Maximum ADS Speed, Reduced Sway Stability" },
    "Vertical Grip I": { name: "Empunhadura Vertical I", description: "Increased Recoil Recovery Time" },
    "Vertical Grip II": { name: "Empunhadura Vertical II", description: "Highly Increased Recoil Recovery Time, Reduced Aim Movement Speed" },
    "Vertical Grip III": { name: "Empunhadura Vertical III", description: "Maximum Recoil Recovery Time, Reduced Aim Movement Speed" },
    "Horizontal Grip": { name: "Empunhadura Horizontal", description: "Increased Hipfire Stability, Increased Aim Walk Speed" },
    "Stable Stock I": { name: "Coronha Estável I", description: "Increased Aim Sway Stability" },
    "Stable Stock II": { name: "Coronha Estável II", description: "Highly Increased Sway Stability, Increased Equip Time" },
    "Stable Stock III": { name: "Coronha Estável III", description: "Maximum Sway Stability, Increased Equip Time" },
    "Lightweight Stock": { name: "Coronha Leve", description: "Increased Aim Movement Speed, Increased Unequip Time" },
    "Kinetic Converter": { name: "Conversor Cinético", description: "Converts Weapon Recoil Force into Micro Shield Regeneration on hit" },
    "Anvil Splitter": { name: "Divisor Anvil", description: "Converts regular ammo into spread armor-shredding flechettes" }
};
